<!doctype html><html lang="sl"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Jivie — izbris računa / Delete account</title>
<style>body{font:16px system-ui,sans-serif;color:#232b38;background:#f7f8fa;max-width:700px;margin:40px auto;padding:20px}h1{font-size:28px}label{display:block;margin:16px 0}input,select,button{font:inherit;padding:10px;max-width:100%;box-sizing:border-box}input[type=password],input[type=text]{display:block;width:100%}button{background:#315ba8;color:white;border:0;border-radius:6px;margin:12px 0}fieldset{border:1px solid #c8ccd3;padding:15px}.error{color:#a82d2d}</style>
<h1>Jivie — izbris računa / Delete account</h1>
<p>Ta stran izbriše vaš Kanboard in FamilyHub račun na tem strežniku. Izdajatelj aplikacije je TriparNA. Lokalni podatki in kopije na drugih napravah se s tem ne izbrišejo. / This page deletes your Kanboard and FamilyHub account on this server. Local data and copies on other devices remain.</p>
<?php if (!$available): ?><p>Ta samostojna namestitev nima omogočenega izbrisa računa. / Account deletion is unavailable on this server.</p><?php else: ?>
<?php if ($error): ?><p class="error">Postopek ni bil potrjen: <?= $this->text->e($error) ?>. Ponovno preglejte podatke in izbire. / The operation was not confirmed. Review the current data and choices again.</p><?php endif ?>
<?php if (isset($state['result'])): ?>
<?php if ($state['result']['deleted']): ?><h2>Račun je izbrisan. / Account deleted.</h2>
<?php elseif ($state['result']['cancelled']??false): ?><h2>Zahteva za izbris je preklicana. / Deletion request cancelled.</h2><p>Ta operacija ne more več izbrisati računa. / This operation cannot delete your account later.</p><a href="<?= $this->url->href('AccountDeletionController','index',['plugin'=>'FamilyHub']) ?>">Nov pregled / Start new review</a>
<?php elseif ($state['result']['cleanupPending']): ?><h2>Račun je odstranjen; čiščenje datotek še poteka. / Account removed; file cleanup pending.</h2><p>Če se čiščenje ne zaključi, naj upravljavec preveri pravice do datotek in zažene ponovno čiščenje. / If cleanup does not finish, the server operator must check file permissions and retry cleanup.</p>
<?php else: ?><p>Izbris še ni potrjen. / Deletion is not confirmed.</p><?php endif ?>
<form method="post" action="<?= $this->url->href('AccountDeletionController','status',['plugin'=>'FamilyHub']) ?>"><?= $csrf ?><input type="hidden" name="operationId" value="<?= $this->text->e($state['operationId']) ?>"><input type="hidden" name="receiptToken" value="<?= $this->text->e($state['receiptToken']) ?>"><button>Preveri stanje / Check status</button></form>
<?php elseif (isset($state['plan'])): $plan=$state['plan']; ?>
<h2>Pregled vpliva / Review impact</h2><p>Izbrišejo se račun, naprave, poverilnice, zasebni prostor in skupni zapisi, ki ste jih ustvarili. Zapisi drugih ustvarjalcev ostanejo, vključno z vašimi urejanji njihove vsebine; reference na vas se odstranijo. Seštevki financ se lahko spremenijo. / Your account, sessions, private space and records you created are removed. Records created by others remain, including your edits to their content; references to your identity are removed. Financial totals may change.</p>
<p>Osebni zapisi / Private records: <?= (int)$plan['impact']['personalRecords'] ?>. Osebne finance / Private finance: <?= (int)$plan['impact']['personalFinanceRecords'] ?>. Naprave / Devices: <?= (int)$plan['impact']['devices'] ?>.</p>
<p>Skupni zapisi za odstranitev / Shared records removed: <?= (int)$plan['impact']['sharedRecordsDeleted'] ?>. Skupne finance za odstranitev / Shared finance removed (where currently visible): <?= (int)$plan['impact']['sharedFinanceRecordsDeleted'] ?>. Kanboard opravila / Kanboard tasks removed: <?= (int)$plan['impact']['kanboardTasksDeleted'] ?>. Komentarji / Comments: <?= (int)$plan['impact']['kanboardCommentsDeleted'] ?>. Priponke / Attachments: <?= (int)$plan['impact']['kanboardFilesDeleted'] ?>.</p>
<?php if (($plan['policyVersion'] ?? 1) === 3): ?>
<h3>Povezana plačila in povračila / Linked payments and reimbursements</h3>
<p>Če prostor ohranite ali prenesete, ostanejo izrecno ohranjeni skupni strošek, zneski, datumi in zgodovinske reference plačil ter povračil. Osebni prikazi in povezave z zasebnimi računi se odstranijo. To ni popolna anonimizacija in ne izbriše že prenesenih kopij. / Keeping or transferring a source space retains the explicitly preserved shared expense, payment and reimbursement amounts, dates and historical references. Private projections and account links are removed. This is not full anonymization and does not erase downloaded copies.</p>
<p>Zasebni prikazi plačil za odstranitev / Private payment projections to remove: <?= (int)$plan['impact']['privatePaymentProjectionsDeleted'] ?>. Že deljena zgodovina plačil / Already shared payment receipts: <?= (int)$plan['impact']['sharedPaymentReceiptsRetained'] ?>.</p>
<?php foreach ($plan['linkedFinancialFacts'] as $fact):
    $scopeName = 'Prej deljeni prostor / Previously shared space';
    foreach ($plan['sharedScopes'] as $sharedScope) {
        if ($sharedScope['id'] === $fact['scopeId']) { $scopeName = $sharedScope['name']; break; }
    }
?>
<p data-linked-payment-scope="<?= $this->text->e($fact['scopeId'] ?? '') ?>"><?= $this->text->e($scopeName) ?>:
ob ohranitvi / if kept: <?= (int)$fact['eventsRetainedIfScopeKept'] ?> plačil / payments;
ob izbrisu / if deleted: <?= (int)$fact['eventsDeletedIfScopeDeleted'] ?> plačil / payments;
<?= (int)$fact['refundLegs'] ?> potrjenih povračil / approved reimbursements.</p>
<?php endforeach; endif ?>
<?php $explanations=['last_admin'=>'Najprej določite drugega aktivnega skrbnika v Kanboardu. / Assign another active Kanboard administrator first.','legacy_task_has_other_contributions'=>'Vaše staro Kanboard opravilo vsebuje prispevke drugih. Pred izbrisom posebej razrešite lastništvo ali izvoz teh prispevkov; ta korak jih ne briše samodejno. / A legacy task you created contains other members’ contributions; resolve their ownership or export before deleting.','legacy_shared_private_project'=>'Zasebni Kanboard projekt vsebuje podatke drugih. Pred izbrisom posebej razrešite te podatke. / A private legacy project contains others’ data and needs separate resolution.','shared_scope_without_successor'=>'Skupni prostor vsebuje podatke drugih, vendar nima aktivnega naslednika. Povabite ustreznega člana in nato prenesite lastništvo. / Shared data have no active successor; invite an appropriate member and transfer ownership.']; ?>
<?php foreach ($plan['blockers'] as $block): if (!in_array($block['code'],['shared_scope_owner','shared_structure_resolution'],true)): ?><p class="error"><?= $this->text->e($explanations[$block['code']]??'Podatki zahtevajo ločeno razrešitev pred izbrisom. / Resolve the affected data separately before deletion.') ?></p><?php endif; endforeach ?>
<form method="post" action="<?= $this->url->href('AccountDeletionController','confirm',['plugin'=>'FamilyHub']) ?>"><?= $csrf ?>
<?php foreach (['token','operationId','receiptToken'] as $key): ?><input type="hidden" name="<?= $key ?>" value="<?= $this->text->e($state[$key]) ?>"><?php endforeach ?><input type="hidden" name="previewHash" value="<?= $this->text->e($plan['previewHash']) ?>"><input type="hidden" name="policyVersion" value="<?= (int)$plan['policyVersion'] ?>">
<?php foreach ($plan['ownedScopes'] as $scope): ?><label>Lastništvo / Ownership: <?= $this->text->e($scope['name']) ?><select name="owners[<?= $this->text->e($scope['id']) ?>]"><option value="">Izberite / Select</option><?php if ($scope['canDeleteScope']): ?><option value="deleteOwnedScope">Izbriši prostor z mojimi podatki / Delete scope with my data</option><?php endif ?><?php foreach ($scope['eligibleSuccessors'] as $member): ?><option value="<?= $this->text->e($member['accountId']) ?>">Prenesi / Transfer: <?= $this->text->e($member['displayName']) ?></option><?php endforeach ?></select></label><?php endforeach ?>
<?php foreach ($plan['resolutions'] as $resolution): ?><label><input type="checkbox" name="structures[]" value="<?= $this->text->e($resolution['scopeId'].':'.$resolution['recordId'].':'.$resolution['action']) ?>"> <?= $this->text->e($resolution['name']??'Skupna struktura brez trenutne pravice do podrobnosti / Shared structure without current access to details') ?>.
<?php if ($resolution['action']==='detachOrganization'): ?> Če izbrišete organizacijo, izrecno ohrani ta projekt kot samostojen prostor. Njegovi člani, vsebina in finančne pravice ostanejo; prenos lastništva organizacije povezave ne odveže. / If you delete the organization, explicitly retain this project as an independent space. Its members, content and financial rights remain; transferring the organization does not detach it.
<?php elseif ($resolution['type']==='financeEntry'): ?> Če prostor ohranite ali prenesete, izrecno ohrani skupni strošek in potrjeno zgodovino plačil ter povračil. Moje osebne opombe in naziv se odstranijo. Če izberete izbris prostora, to ohranitev prezrite. / If the space is kept or transferred, explicitly retain the shared expense and approved payment and reimbursement history, removing my personal notes and title. This choice is unnecessary when deleting its source space.
<?php elseif ($resolution['type']==='project'): ?> Izrecno ohrani anonimizirano strukturo projekta in identifikatorje faz, da opravila drugih ostanejo povezana in uporabna. Vaš naslov, opis in besedila faz se odstranijo. / Explicitly preserve an anonymized project structure and phase identifiers so others’ tasks remain linked and editable. Your title, description and phase text are removed.
<?php elseif ($resolution['type']==='householdPerson'): ?> Izrecno ohrani anonimiziran, arhiviran profil osebe, na katerega se sklicujejo podatki drugih; ime in zapiski se odstranijo. Profil ne daje prijave ali dostopnih pravic. / Explicitly retain an anonymized archived person profile referenced by others’ data; name and notes are removed. The profile grants no login or access rights.
<?php else: ?><?php if (isset($resolution['currency'],$resolution['openingBalanceMinor'])): ?> <?= $this->text->e(number_format($resolution['openingBalanceMinor']/100,2,',','.').' '.$resolution['currency']) ?> (začetno stanje / opening balance).<?php endif ?> Izrecno ohrani generično strukturo skupnega <?= $resolution['type']==='shoppingList'?'seznama':'finančnega računa' ?> za podatke drugih članov; pri računu ostaneta valuta in morebitno začetno stanje. / Explicitly keep generic shared structure for other members; financial account currency and any opening balance remain.
<?php endif ?></label><?php endforeach ?>
<label>Geslo / Password<input type="password" name="password" required autocomplete="current-password"></label><label>Sveža 2FA koda, če je omogočena / Fresh 2FA code if enabled<input type="text" name="otp" inputmode="numeric" autocomplete="one-time-code"></label><label>Za potrditev vpišite DELETE / Type DELETE to confirm<input type="text" name="confirmation" required pattern="DELETE" autocomplete="off"></label><button>Trajno izbriši račun / Permanently delete account</button> <button formnovalidate formaction="<?= $this->url->href('AccountDeletionController','cancelPending',['plugin'=>'FamilyHub']) ?>">Prekliči to zahtevo / Cancel this request</button></form>
<?php else: ?>
<p>Prijavite se v svoj račun, preglejte vpliv, nato posebej potrdite trajni izbris. / Sign into your own account, review the impact, then explicitly confirm permanent deletion.</p>
<form method="post" action="<?= $this->url->href('AccountDeletionController','preview',['plugin'=>'FamilyHub']) ?>"><?= $csrf ?><label>Uporabniško ime / Username<input type="text" name="username" required autocomplete="username"></label><label>Geslo / Password<input type="password" name="password" required autocomplete="current-password"></label><label>2FA koda, če je omogočena / 2FA code if enabled<input type="text" name="otp" inputmode="numeric" autocomplete="one-time-code"></label><button>Preglej izbris / Review deletion</button></form>
<?php endif; endif ?></html>
