<?php
umask(0077);
$port=random_int(30000,40000);define('FAMILYHUB_ACCOUNT_MAIL_KEY_BASE64',base64_encode(random_bytes(32)));define('FAMILYHUB_SMTP_HOST','127.0.0.1');define('FAMILYHUB_SMTP_PORT',$port);define('FAMILYHUB_SMTP_ENCRYPTION','none');define('FAMILYHUB_SMTP_ALLOW_LOCAL_PLAINTEXT',true);define('FAMILYHUB_SMTP_FROM','sender@capture.invalid');define('MAIL_BCC',['forbidden@capture.invalid']);
require '/var/www/app/app/common.php';if(session_status()===PHP_SESSION_ACTIVE){session_abort();}
if(!defined('FAMILYHUB_DEVELOPMENT_MODE')||FAMILYHUB_DEVELOPMENT_MODE!==true){throw new RuntimeException('Synthetic only');}
use Kanboard\Plugin\FamilyHub\Model\NativeService;
use Kanboard\Plugin\FamilyHub\Model\NativeError;
use Kanboard\Plugin\FamilyHub\Model\NativeAccountMailQueue;
use Kanboard\Plugin\FamilyHub\Model\NativeAccountMailCrypto;
use Kanboard\Plugin\FamilyHub\Model\NativeAccountTokens;
$pdo=$container['db']->getConnection();$checks=0;$prefix='account_'.bin2hex(random_bytes(5));$ip='synthetic-account-'.bin2hex(random_bytes(6));$service=new NativeService($container);$output='/tmp/familyhub-smtp-'.bin2hex(random_bytes(8)).'.json';
function check($v,$m){global$checks;if(!$v){throw new RuntimeException('FAIL: '.$m);}$checks++;echo 'PASS: '.$m.PHP_EOL;}
function api($op,$p,$token=''){global$service,$ip;return$service->dispatch($op,$p,$token?'Bearer '.$token:'',$ip);}
function deny($op,$p,$token,$code,$m){try{api($op,$p,$token);$v=false;}catch(NativeError$e){$v=$e->errorCode===$code;}check($v,$m);}
function query($sql,$p=[]){global$pdo;$q=$pdo->prepare($sql);$q->execute($p);$rows=$q->fetchAll(PDO::FETCH_ASSOC);$q->closeCursor();return$rows;}
function latest($account,$purpose){return query('SELECT * FROM familyhub_account_tokens WHERE account_id=? AND purpose=? ORDER BY created_at DESC,id DESC',[$account,$purpose])[0];}
function live($account,$purpose){return query('SELECT * FROM familyhub_account_tokens WHERE account_id=? AND purpose=? AND consumed_at IS NULL AND revoked_at IS NULL',[$account,$purpose])[0];}
function plain($row){global$container;$job=query('SELECT token_cipher FROM familyhub_account_mail WHERE token_id=?',[$row['id']])[0];return NativeAccountMailCrypto::decrypt($job['token_cipher'],(new NativeAccountTokens($container))->aad($row['id'],$row['account_id']));}
function race(array$requests){$children=[];$paths=[];try{foreach($requests as$r){$path='/tmp/familyhub-account-race-'.bin2hex(random_bytes(8)).'.json';file_put_contents($path,json_encode($r));chmod($path,0600);$paths[]=$path;$proc=proc_open([PHP_BINARY,'/familyhub-tests/account-race-child.php',$path],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);stream_set_timeout($pipes[1],20);if(trim(fgets($pipes[1]))!=='ready'){throw new RuntimeException('Race worker unavailable');}$children[]=[$proc,$pipes];}foreach($children as[$proc,$pipes]){fwrite($pipes[0],"go\n");fflush($pipes[0]);}$out=[];foreach($children as[$proc,$pipes]){$line=fgets($pipes[1]);$out[]=json_decode($line,true,32,JSON_THROW_ON_ERROR);foreach($pipes as$p){fclose($p);}proc_close($proc);}return$out;}finally{foreach($paths as$path){@unlink($path);}}}
$process=proc_open([PHP_BINARY,'/familyhub-tests/smtp-capture.php',$output,(string)$port],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);stream_set_timeout($pipes[1],5);if(trim(fgets($pipes[1]))!=='ready'){throw new RuntimeException('Capture unavailable');}
try{
$pw=bin2hex(random_bytes(16));foreach(['a','b','c','d']as$s){$ids[$s]=$container['userModel']->create(['username'=>$prefix.'_'.$s,'password'=>$pw,'email'=>$s.'@unverified.invalid','role'=>'app-user']);$sessions[$s]=api('auth.login',['username'=>$prefix.'_'.$s,'password'=>$pw,'deviceName'=>'Account test']);}$a=$sessions['a'];$token=$a['token'];$account=$a['user']['accountId'];$foreign=$sessions['b']['token'];
$cap=api('capabilities',[]);check($cap['features']['emailVerification']&&$cap['features']['passwordReset'],'configured SMTP and separate key advertise account email');$status=api('account.status',[],$token);check($status['email']===null&&!$status['emailVerified']&&!$status['resetAvailable'],'existing core email is not implicitly verified');
check(api('auth.reset.request',['username'=>$prefix.'_a','language'=>'sl'])===api('auth.reset.request',['username'=>$prefix.'_absent','language'=>'sl']),'reset response indistinguishable for unknown and unverified account');check(count(query('SELECT id FROM familyhub_account_tokens WHERE account_id=?',[$account]))===0,'unverified core email never receives reset code');
deny('account.status',[],'','auth_required','account status requires device bearer');deny('account.email.request',['email'=>'a@capture.invalid','language'=>'sl','password'=>'wrong-password'],$sessions['c']['token'],'invalid_credentials','email recovery change requires current password');check(query('SELECT nb_failed_login FROM users WHERE id=?',[$ids['c']])[0]['nb_failed_login']==1,'failed email step-up counter commits');
check(api('account.email.request',['email'=>'a@capture.invalid','language'=>'sl','password'=>$pw],$token)['accepted'],'email verification durably queued');$row=live($account,'verify');$code=plain($row);check(!str_contains(json_encode(query('SELECT * FROM familyhub_account_tokens WHERE id=?',[$row['id']])),$code),'verification database stores hash only');check(!str_contains(query('SELECT token_cipher FROM familyhub_account_mail WHERE token_id=?',[$row['id']])[0]['token_cipher'],$code),'queued code encrypted separately from login secrets');
try{NativeAccountMailCrypto::decrypt(query('SELECT token_cipher FROM familyhub_account_mail WHERE token_id=?',[$row['id']])[0]['token_cipher'],'wrong-binding');$v=false;}catch(Throwable$e){$v=true;}check($v,'mail cipher rejects altered account/token binding');
deny('account.email.confirm',['token'=>$code],$foreign,'account_token_invalid','verification code bound to intended account');
$counts=(new NativeAccountMailQueue($container))->run(20);check($counts['accepted']===1,'local SMTP captures verification code from durable queue');$messages=json_decode(file_get_contents($output),true)['messages'];check(count($messages)===1&&$messages[0]['recipients']===['a@capture.invalid']&&!str_contains($messages[0]['body'],'forbidden@'),'security mail ignores global BCC and delivers only designated address');check(str_contains(quoted_printable_decode($messages[0]['body']),$code)&&!str_contains($messages[0]['body'],'http'),'code appears only in SMTP body with no URL');check(query('SELECT token_cipher FROM familyhub_account_mail WHERE token_id=?',[$row['id']])[0]['token_cipher']===null,'accepted mail clears encrypted pending code');check((new NativeAccountMailQueue($container))->run(20)['accepted']===0,'accepted account mail not resent on cron replay');
check(api('account.email.confirm',['token'=>$code],$token)['verified'],'email confirmation accepted once');deny('account.email.confirm',['token'=>$code],$token,'account_token_invalid','verification code replay denied');$status=api('account.status',[],$token);check($status['email']==='a@capture.invalid'&&$status['emailVerified']&&$status['resetAvailable'],'only confirmed address enables reset');
api('auth.reset.request',['username'=>$prefix.'_a','language'=>'en']);$resetRow=live($account,'reset');$oldReset=plain($resetRow);
api('account.email.request',['email'=>'a2@capture.invalid','language'=>'sl','password'=>$pw],$token);$verifyRow=live($account,'verify');$staleVerify=plain($verifyRow);check(api('account.status',[],$token)['email']==='a@capture.invalid','verified address unchanged while replacement pending');deny('auth.reset.confirm',['token'=>$oldReset,'password'=>'changed-password-123'],'','account_token_invalid','recovery code invalidated by newer identity revision');
api('account.email.request',['email'=>'a3@capture.invalid','language'=>'en','password'=>$pw],$token);$newVerify=plain(live($account,'verify'));deny('account.email.confirm',['token'=>$staleVerify],$token,'account_token_invalid','new verification invalidates older pending code');check(api('account.email.confirm',['token'=>$newVerify],$token)['verified'],'latest verification updates recovery address');check(count(query('SELECT id FROM familyhub_account_tokens WHERE account_id=? AND purpose=\'reset\' AND revoked_at IS NULL AND consumed_at IS NULL',[$account]))===0,'email confirmation revokes previous reset tokens');
api('auth.reset.request',['username'=>$prefix.'_a','language'=>'en']);$resetRow=live($account,'reset');$resetCode=plain($resetRow);$second=api('auth.login',['username'=>$prefix.'_a','password'=>$pw,'deviceName'=>'Second device']);$pdo->prepare('INSERT INTO familyhub_push_registrations VALUES(?,?,?, ?,\'synthetic-project\',\'ios\',\'sl\',1,1,?)')->execute([$a['device']['id'],$account,hash('sha256','synthetic-token-'.$prefix),'synthetic-cipher',time()]);
$pdo->prepare('INSERT INTO familyhub_push_jobs(inbox_id,device_id,registration_revision,token_hash,state,attempts,next_attempt,expires_at) VALUES(1,?,1,?,\'pending\',0,0,?)')->execute([$a['device']['id'],hash('sha256','synthetic-token-'.$prefix),time()+3600]);
$base=['operation'=>'auth.reset.confirm','params'=>['token'=>$resetCode,'password'=>'fresh-password-123'],'mailKey'=>FAMILYHUB_ACCOUNT_MAIL_KEY_BASE64,'ip'=>'synthetic-race-'.bin2hex(random_bytes(8))];$out=race([$base,$base]);check(count(array_filter($out,fn($r)=>$r['ok']))===1&&count(array_filter($out,fn($r)=>($r['error']??'')==='account_token_invalid'))===1,'two simultaneous reset code uses allow exactly one success');
check((int)query('SELECT active FROM familyhub_push_registrations WHERE device_id=?',[$a['device']['id']])[0]['active']===0&&query('SELECT state FROM familyhub_push_jobs WHERE device_id=?',[$a['device']['id']])[0]['state']==='cancelled','reset atomically revokes push registrations and queued generations');
deny('auth.me',[],$token,'device_revoked','reset revokes first session');deny('auth.me',[],$second['token'],'device_revoked','reset revokes every other device');deny('auth.login',['username'=>$prefix.'_a','password'=>$pw,'deviceName'=>'Old password'],'','invalid_credentials','old password cannot authenticate after reset');check(api('auth.login',['username'=>$prefix.'_a','password'=>'fresh-password-123','deviceName'=>'New login'])['user']['accountId']===$account,'new password login preserves durable account');
// Genuine concurrency: account c has no private map before both workers start.
$personal=['operation'=>'personal.ensure','params'=>[],'bearer'=>'Bearer '.$sessions['c']['token'],'ip'=>'synthetic-race-'.bin2hex(random_bytes(8))];$out=race([$personal,$personal]);check($out[0]['ok']&&$out[1]['ok']&&$out[0]['scopeId']===$out[1]['scopeId'],'simultaneous personal ensure creates one scope');check(count(query('SELECT scope_id FROM familyhub_personal_scopes WHERE account_id=?',[$sessions['c']['user']['accountId']]))===1,'personal singleton durable unique binding');
// TOTP setup, missing factor, replay, and preservation after reset.
$uid=$ids['b'];$b=$sessions['b'];$secret=\Otp\GoogleAuthenticator::generateRandom();query('UPDATE users SET twofactor_activated=1,twofactor_secret=? WHERE id=?',[$secret,$uid]);$otp=(new \Otp\Otp())->totp(\Base32\Base32::decode($secret),intdiv(time(),30));$session=api('auth.login',['username'=>$prefix.'_b','password'=>$pw,'deviceName'=>'TOTP','otp'=>$otp]);$bt=$session['token'];deny('account.email.request',['email'=>'b@capture.invalid','language'=>'sl','password'=>$pw],$bt,'two_factor_required','email step-up requires configured TOTP');deny('account.email.request',['email'=>'b@capture.invalid','language'=>'sl','password'=>$pw,'otp'=>$otp],$bt,'invalid_credentials','email step-up cannot replay login TOTP');$next=(new \Otp\Otp())->totp(\Base32\Base32::decode($secret),intdiv(time(),30)+1);api('account.email.request',['email'=>'b@capture.invalid','language'=>'sl','password'=>$pw,'otp'=>$next],$bt);$bcode=plain(live($b['user']['accountId'],'verify'));api('account.email.confirm',['token'=>$bcode],$bt);api('auth.reset.request',['username'=>$prefix.'_b','language'=>'sl']);$r=live($b['user']['accountId'],'reset');$rc=plain($r);deny('auth.reset.confirm',['token'=>$rc,'password'=>'totp-fresh-password'],'','two_factor_required','email reset cannot bypass TOTP');deny('auth.reset.confirm',['token'=>$rc,'password'=>'totp-fresh-password','otp'=>$next],'','invalid_credentials','reset rejects already used TOTP');$freshStep=intdiv(time(),30);query('UPDATE familyhub_totp_state SET last_step=? WHERE user_id=?',[$freshStep-1,$uid]);$freshOtp=(new \Otp\Otp())->totp(\Base32\Base32::decode($secret),$freshStep);check(api('auth.reset.confirm',['token'=>$rc,'password'=>'totp-fresh-password','otp'=>$freshOtp])['reset'],'reset with fresh valid TOTP succeeds');check((int)query('SELECT twofactor_activated FROM users WHERE id=?',[$uid])[0]['twofactor_activated']===1,'reset preserves configured two factor');
// Test-only fresh state above adjusts only this synthetic user's replay step.
check(api('auth.reset.request',['username'=>$prefix.'_ldap','language'=>'sl'])===['accepted'=>true],'unsupported or absent provider stays generic accepted');
// Expired/consumed jobs cancel, strict limit, bounded retry and expired lease recovery.
$c=$sessions['c'];api('account.email.request',['email'=>'c@capture.invalid','language'=>'sl','password'=>$pw],$c['token']);$cRow=live($c['user']['accountId'],'verify');$cCode=plain($cRow);query('UPDATE familyhub_account_tokens SET expires_at=0 WHERE id=?',[$cRow['id']]);deny('account.email.confirm',['token'=>$cCode],$c['token'],'account_token_invalid','expired verification code rejected');$before=count(json_decode(file_get_contents($output),true)['messages']);check((new NativeAccountMailQueue($container))->run(20)['cancelled']>=1&&count(json_decode(file_get_contents($output),true)['messages'])===$before,'expired or invalidated codes never sent by cron');
try{(new NativeAccountMailQueue($container))->run(51);$v=false;}catch(NativeError$e){$v=$e->errorCode==='validation_error';}check($v,'security mail dispatch limit bounded');
$d=$sessions['d'];api('account.email.request',['email'=>'d@capture.invalid','language'=>'en','password'=>$pw],$d['token']);$dRow=live($d['user']['accountId'],'verify');
file_put_contents($output.'.mode','reject');$result=(new NativeAccountMailQueue($container))->run(20);$job=query('SELECT * FROM familyhub_account_mail WHERE token_id=?',[$dRow['id']])[0];check($result['retry']>=1&&$job['state']==='pending'&&(int)$job['attempts']===1&&(int)$job['next_attempt']>time(),'SMTP rejection preserves encrypted job with bounded retry');
query('UPDATE familyhub_account_mail SET state=\'processing\',lease_token=\'synthetic-lease\',lease_until=? WHERE token_id=?',[time()+100,$dRow['id']]);$before=count(json_decode(file_get_contents($output),true)['messages']);check((new NativeAccountMailQueue($container))->run(20)['accepted']===0&&count(json_decode(file_get_contents($output),true)['messages'])===$before,'active account-mail lease excludes competing worker');
file_put_contents($output.'.mode','accept');query('UPDATE familyhub_account_mail SET lease_until=0 WHERE token_id=?',[$dRow['id']]);check((new NativeAccountMailQueue($container))->run(20)['accepted']===1&&count(json_decode(file_get_contents($output),true)['messages'])===$before+1,'expired mail lease recovered and accepted once');
api('account.email.request',['email'=>'d2@capture.invalid','language'=>'sl','password'=>$pw],$d['token']);$invalidated=live($d['user']['accountId'],'verify');query('UPDATE users SET password=? WHERE id=?',[password_hash('changed-outside-app',PASSWORD_BCRYPT),$ids['d']]);$before=count(json_decode(file_get_contents($output),true)['messages']);check((new NativeAccountMailQueue($container))->run(20)['cancelled']>=1&&count(json_decode(file_get_contents($output),true)['messages'])===$before,'password change cancels pending security mail before SMTP');
// Durable rate buckets for only a synthetic key; no production limits disabled.
$key='synthetic-account-rate-'.bin2hex(random_bytes(8));$db=new NativeService($container);for($n=0;$n<3;$n++){$db->rate([[$key,3,900]]);}try{$db->rate([[$key,3,900]]);$limited=false;}catch(NativeError$e){$limited=$e->errorCode==='rate_limited';}check($limited,'account email/reset request budget uses durable rate limiting');
echo 'SUCCESS '.$checks.' account checks ('.$pdo->getAttribute(PDO::ATTR_DRIVER_NAME).', local SMTP only)'.PHP_EOL;
}finally{foreach($sessions??[]as$session){query('UPDATE familyhub_account_tokens SET revoked_at=? WHERE account_id=? AND consumed_at IS NULL AND revoked_at IS NULL',[time(),$session['user']['accountId']]);query('UPDATE familyhub_account_mail SET state=\'cancelled\',token_cipher=NULL WHERE token_id IN (SELECT id FROM familyhub_account_tokens WHERE account_id=?) AND state<>\'accepted\'',[$session['user']['accountId']]);}proc_terminate($process);foreach($pipes as$p){if(is_resource($p)){fclose($p);}}proc_close($process);@unlink($output);@unlink($output.'.mode');}
