<?php
require '/var/www/app/app/common.php'; if(session_status()===PHP_SESSION_ACTIVE){session_abort();}
if(!defined('FAMILYHUB_DEVELOPMENT_MODE') || FAMILYHUB_DEVELOPMENT_MODE!==true){throw new RuntimeException('Synthetic only');}
use Kanboard\Plugin\FamilyHub\Model\NativeService;use Kanboard\Plugin\FamilyHub\Model\NativeError;
$p=$container['db']->getConnection();$s=new NativeService($container);$ip='delete-'.bin2hex(random_bytes(6));$checks=0;
function ck($v,$m){global $checks;if(!$v)throw new RuntimeException('FAIL '.$m);$checks++;echo 'PASS '.$m.PHP_EOL;}
function api($o,$a=[],$t=''){global $s,$ip;return $s->dispatch($o,$a,$t?'Bearer '.$t:'',$ip);}
function q($sql,$a=[]){global $p;$r=$p->prepare($sql);$r->execute($a);$v=$r->fetchAll(PDO::FETCH_ASSOC);$r->closeCursor();return $v;}
function uid(){ $h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20); }
function deny($o,$a,$t,$code,$m){try{api($o,$a,$t);$ok=false;}catch(NativeError $e){$ok=$e->errorCode===$code;}ck($ok,$m);}
$prefix='del_'.bin2hex(random_bytes(5));$pw='password-'.bin2hex(random_bytes(12));$sessions=[];
foreach(['a','b','c','d','e'] as $n){$ids[$n]=$container['userModel']->create(['username'=>$prefix.'_'.$n,'password'=>$pw,'role'=>'app-user']);$sessions[$n]=api('auth.login',['username'=>$prefix.'_'.$n,'password'=>$pw,'deviceName'=>'Deletion test']);}
$a=$sessions['a'];$b=$sessions['b'];$c=$sessions['c'];$d=$sessions['d'];$aid=$a['user']['accountId'];$bid=$b['user']['accountId'];
ck(api('capabilities')['features']['accountDeletion'],'self-hosted advertises deletion');
deny('account.deletion.preview',[], '', 'auth_required','preview needs bearer');
$personal=api('personal.ensure',[],$a['token'])['scope']['id'];$scope=uid();api('scopes.create',['id'=>$scope,'kind'=>'household','name'=>'Test home','requestId'=>uid()],$a['token']);
q("INSERT INTO familyhub_members(scope_id,user_id,account_id,role,active) VALUES(?,?,?,'member',1)",[$scope,$ids['b'],$bid]);
$now=gmdate('Y-m-d\TH:i:s\Z');$ownProject=uid();$otherTask=uid();$ownList=uid();$otherItem=uid();$ownFinance=uid();$otherEntry=uid();$ownEntry=uid();$ownTask=uid();
function generic($scope,$id,$type,$payload,$account){$json=json_encode($payload,JSON_THROW_ON_ERROR);q('INSERT INTO familyhub_records(scope_id,id,type,revision,deleted,payload,sequence,updated_at,contract_version,created_by,updated_by) VALUES(?,?,?,1,0,?,1,?,2,?,?)',[$scope,$id,$type,$json,gmdate('Y-m-d\TH:i:s\Z'),$account,$account]);}
function finance($scope,$id,$type,$payload,$account){q('INSERT INTO familyhub_finance_records(scope_id,id,type,revision,deleted,payload,sequence,updated_at,created_by,updated_by) VALUES(?,?,?,1,0,?,1,?,?,?)',[$scope,$id,$type,json_encode($payload),gmdate('Y-m-d\TH:i:s\Z'),$account,$account]);}
generic($scope,$ownProject,'project',['title'=>'secret-own-project','description'=>'private-own-description','area'=>'home','createdAt'=>$now,'updatedAt'=>$now,'startAt'=>null,'endAt'=>null],$aid);
generic($scope,$otherTask,'task',['title'=>'other-task','notes'=>'other notes','projectId'=>$ownProject,'dueAt'=>null,'isCompleted'=>false,'createdAt'=>$now,'updatedAt'=>$now,'startAt'=>null,'endAt'=>null,'assigneeAccountIds'=>[$aid,$bid]],$bid);
generic($scope,$ownTask,'task',['title'=>'own-task-private','notes'=>'own notes','projectId'=>null,'dueAt'=>null,'isCompleted'=>false,'createdAt'=>$now,'updatedAt'=>$now,'startAt'=>null,'endAt'=>null,'assigneeAccountIds'=>[]],$aid);
generic($scope,$ownList,'shoppingList',['title'=>'own-list-secret','createdAt'=>$now,'updatedAt'=>$now],$aid);
generic($scope,$otherItem,'shoppingItem',['title'=>'other item','listId'=>$ownList,'quantity'=>'2','isChecked'=>false,'createdAt'=>$now,'updatedAt'=>$now],$bid);
q('INSERT INTO familyhub_finance_policy VALUES(?,1,1,1)',[$scope]);q("INSERT INTO familyhub_finance_grants VALUES(?,?,'write')",[$scope,$aid]);q("INSERT INTO familyhub_finance_grants VALUES(?,?,'write')",[$scope,$bid]);
finance($scope,$ownFinance,'financeAccount',['name'=>'own account-secret','currency'=>'EUR','openingBalanceMinor'=>12300,'ownerAccountId'=>$aid,'createdAt'=>$now,'updatedAt'=>$now],$aid);
foreach([[$otherEntry,$bid,'other-finance'],[$ownEntry,$aid,'own-finance-secret']] as [$entry,$actor,$title]){finance($scope,$entry,'financeEntry',['accountId'=>$ownFinance,'kind'=>'expense','status'=>'posted','amountMinor'=>100,'currency'=>'EUR','title'=>$title,'notes'=>'notes','category'=>'test','payerAccountId'=>$aid,'recipientAccountId'=>null,'occurredAt'=>$now,'createdAt'=>$now,'updatedAt'=>$now],$actor);q('INSERT INTO familyhub_finance_audit VALUES(?,?,1,?,?,NULL,?,?)',[$scope,$entry,$actor,$now,json_encode(['payload'=>['payerAccountId'=>$aid,'title'=>$title]]),uid()]);}
q('INSERT INTO familyhub_finance_audit VALUES(?,?,2,?,?,NULL,?,?)',[$scope,$ownFinance,$bid,$now,json_encode(['payload'=>['name'=>'old-secret-account-name','ownerAccountId'=>$aid]]),uid()]);
q("UPDATE familyhub_finance_grants SET access_level='none' WHERE scope_id=? AND account_id=?",[$scope,$aid]);$restricted=api('account.deletion.preview',[],$a['token']);$rr=array_values(array_filter($restricted['resolutions'],fn($r)=>$r['type']==='financeAccount'))[0];ck($rr['name']===null&&!isset($rr['currency'],$rr['openingBalanceMinor'])&&$rr['recordId']!==$ownFinance,'revoked finance access reveals no name balance currency or record UUID');q("UPDATE familyhub_finance_grants SET access_level='write' WHERE scope_id=? AND account_id=?",[$scope,$aid]);
$foreignOp=uid();q('INSERT INTO familyhub_operations VALUES(?,?,?,?,?,200)',[$scope,$ids['b'],$foreignOp,'hash',json_encode(['record'=>['id'=>$ownProject,'payload'=>['title'=>'secret-own-project']]])]);
$plan=api('account.deletion.preview',[],$a['token']);ck(!$plan['canDelete']&&count($plan['ownedScopes'])===1&&count($plan['resolutions'])===2,'preview requires successor and explicit structure decisions');ck($plan['resolutions'][1]['openingBalanceMinor']===12300 || $plan['resolutions'][0]['openingBalanceMinor']===12300,'authorized finance preview shows retained opening balance');
$params=['operationId'=>uid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$plan['previewHash'],'password'=>$pw,'confirmation'=>'DELETE'];
deny('account.deletion.confirm',$params,$a['token'],'deletion_blocked','no silent ownership or structure preservation');
$params['ownershipTransfers']=[['scopeId'=>$scope,'successorAccountId'=>$bid]];$params['resolutions']=array_map(fn($r)=>['scopeId'=>$r['scopeId'],'recordId'=>$r['recordId'],'action'=>'preserveStructure'],$plan['resolutions']);
$bad=$params;$bad['password']='wrong-password';deny('account.deletion.confirm',$bad,$a['token'],'invalid_credentials','deletion requires fresh password');ck((int)q('SELECT nb_failed_login FROM users WHERE id=?',[$ids['a']])[0]['nb_failed_login']===1,'failed step-up counters committed');
$bad=$params;$bad['previewHash']=str_repeat('0',64);deny('account.deletion.confirm',$bad,$a['token'],'deletion_preview_stale','stale preview cannot delete');
$res=api('account.deletion.confirm',$params,$a['token']);ck($res['deleted']&&!$res['cleanupPending'],'native confirm actually deletes');ck(!q('SELECT id FROM users WHERE id=?',[$ids['a']]),'real Kanboard users row removed');ck(!q('SELECT id FROM familyhub_scopes WHERE id=?',[$personal]),'private scope removed');ck((int)q('SELECT owner_id FROM familyhub_scopes WHERE id=?',[$scope])[0]['owner_id']===$ids['b'],'ownership transferred to selected member');
$r=q('SELECT * FROM familyhub_records WHERE scope_id=? AND id=?',[$scope,$ownProject])[0];ck((int)$r['deleted']===1&&$r['payload']===null&&$r['created_by']===null,'own shared project tombstone contains no content or author');$r=q('SELECT * FROM familyhub_records WHERE id=?',[$otherTask])[0];$payload=json_decode($r['payload'],true);ck($payload['title']==='other-task'&&$payload['projectId']===null&&$payload['assigneeAccountIds']===[$bid]&&(int)$r['revision']===2,'other task preserved, project and assignee references removed with revision');$r=q('SELECT * FROM familyhub_records WHERE id=?',[$ownList])[0];ck(json_decode($r['payload'],true)['title']==='Shared shopping list'&&(int)$r['deleted']===0,'explicit generic shopping structure retains foreign item');
$r=q('SELECT * FROM familyhub_finance_records WHERE id=?',[$ownFinance])[0];$fp=json_decode($r['payload'],true);ck($fp['name']==='Shared financial account'&&$fp['openingBalanceMinor']===12300&&$fp['ownerAccountId']===null,'explicit finance structure preserves currency and opening balance');$r=q('SELECT * FROM familyhub_finance_records WHERE id=?',[$ownEntry])[0];ck((int)$r['deleted']===1&&$r['payload']===null,'own shared finance entry removed');$r=q('SELECT * FROM familyhub_finance_records WHERE id=?',[$otherEntry])[0];ck(json_decode($r['payload'],true)['payerAccountId']===null&&json_decode($r['payload'],true)['title']==='other-finance','foreign finance record retains business data and removes identity');$audit=q('SELECT * FROM familyhub_finance_audit WHERE record_id=?',[$otherEntry])[0];ck($audit['actor_account_id']===$bid&&!str_contains($audit['after_json'],$aid),'foreign audit retained with only identity redaction');ck(!q('SELECT * FROM familyhub_finance_audit WHERE actor_account_id=?',[$aid]),'own audits removed');ck(!q('SELECT * FROM familyhub_finance_audit WHERE record_id=?',[$ownFinance]),'preserved generic financial account loses old personal names from foreign audit snapshots');$replay=q('SELECT * FROM familyhub_operations WHERE id=?',[$foreignOp])[0];ck($replay['request_hash']==='hash'&&(int)$replay['status']===409&&!str_contains($replay['response'],'secret-own-project'),'foreign replay copy redacted without dropping idempotency evidence');
ck(api('account.deletion.status',['operationId'=>$params['operationId'],'receiptToken'=>$params['receiptToken']])['deleted'],'lost ACK recovered without bearer');ck(!api('account.deletion.status',['operationId'=>$params['operationId'],'receiptToken'=>str_repeat('1',64)])['deleted'],'wrong receipt reveals no success');deny('auth.me',[],$a['token'],'device_revoked','old bearer has no remaining permissions');
// Sole-owner shared scopes can be explicitly deleted, without successor.
$single=uid();api('scopes.create',['id'=>$single,'kind'=>'project','name'=>'Own only','requestId'=>uid()],$c['token']);$plan=api('account.deletion.preview',[],$c['token']);ck($plan['ownedScopes'][0]['canDeleteScope'],'sole owner can explicitly delete own scope');$op=['operationId'=>uid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$plan['previewHash'],'password'=>$pw,'confirmation'=>'DELETE','ownedScopeDeletions'=>[$single]];ck(api('account.deletion.confirm',$op,$c['token'])['deleted']&&!q('SELECT id FROM familyhub_scopes WHERE id=?',[$single]),'explicit scope deletion works');
// Avatar bytes are removed only after SQL success; non-existing path retry idempotent.
$avatar='avatars/'.$ids['d'].'/'.bin2hex(random_bytes(10));$blob='synthetic avatar';$container['objectStorage']->put($avatar,$blob);q('UPDATE users SET avatar_path=? WHERE id=?',[$avatar,$ids['d']]);$plan=api('account.deletion.preview',[],$d['token']);$op=['operationId'=>uid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$plan['previewHash'],'password'=>$pw,'confirmation'=>'DELETE'];ck(api('account.deletion.confirm',$op,$d['token'])['deleted'],'avatar cleanup completes after database commit');ck(!file_exists($container['objectStorage']->getSanitizedFilePath($avatar)),'avatar bytes removed');ck(api('account.deletion.status',['operationId'=>$op['operationId'],'receiptToken'=>$op['receiptToken']])['deleted'],'file cleanup status idempotent after missing file');
// Persistent postcommit file failure remains pending and can be retried safely.
$e=$sessions['e'];$avatar='avatars/'.$ids['e'].'/'.bin2hex(random_bytes(10));$blob='pending avatar';$originalStorage=$container['objectStorage'];$originalStorage->put($avatar,$blob);q('UPDATE users SET avatar_path=? WHERE id=?',[$avatar,$ids['e']]);$op=argsForPending($e,$pw);
function argsForPending($session,$password){$plan=api('account.deletion.preview',[],$session['token']);return ['operationId'=>uid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$plan['previewHash'],'password'=>$password,'confirmation'=>'DELETE'];}
unset($container['objectStorage']);$container['objectStorage']=new class($originalStorage){private $storage;public function __construct($storage){$this->storage=$storage;}public function getSanitizedFilePath($path){return $this->storage->getSanitizedFilePath($path);}public function remove($path){return false;}};
try{$result=api('account.deletion.confirm',$op,$e['token']);ck(!$result['deleted']&&$result['cleanupPending']&&!q('SELECT id FROM users WHERE id=?',[$ids['e']]),'postcommit file failure reports pending and retains no account');ck(count(q('SELECT path FROM familyhub_deletion_files WHERE operation_id=?',[$op['operationId']]))===1,'pending file cleanup survives in durable queue');}finally{unset($container['objectStorage']);$container['objectStorage']=$originalStorage;}$result=api('account.deletion.status',['operationId'=>$op['operationId'],'receiptToken'=>$op['receiptToken']]);ck($result['deleted']&&!$result['cleanupPending']&&!file_exists($originalStorage->getSanitizedFilePath($avatar)),'receipt retry completes pending file removal without bearer');
// After the earlier author has deleted their account, payloadless tombstones
// and nonpersonal structural records must not trap the final household member.
$plan=api('account.deletion.preview',[],$b['token']);$own=array_values(array_filter($plan['ownedScopes'],fn($r)=>$r['id']===$scope))[0];ck($own['canDeleteScope'],'last remaining member may delete resolved household');$op=['operationId'=>uid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$plan['previewHash'],'password'=>$pw,'confirmation'=>'DELETE','ownedScopeDeletions'=>[$scope]];ck(api('account.deletion.confirm',$op,$b['token'])['deleted']&&!q('SELECT id FROM familyhub_scopes WHERE id=?',[$scope]),'B then A deletion chain does not leave permanent owner blocker');
echo 'SUCCESS '.$checks.' deletion checks ('.$p->getAttribute(PDO::ATTR_DRIVER_NAME).')'.PHP_EOL;
