<?php
require '/var/www/app/app/common.php'; if(session_status()===PHP_SESSION_ACTIVE){session_abort();}
if(!defined('FAMILYHUB_DEVELOPMENT_MODE') || FAMILYHUB_DEVELOPMENT_MODE!==true){throw new RuntimeException('Synthetic only');}
use Kanboard\Plugin\FamilyHub\Model\NativeService;use Kanboard\Plugin\FamilyHub\Model\NativeError;
$p=$container['db']->getConnection();$s=new NativeService($container);$ip='delete-'.bin2hex(random_bytes(6));$checks=0;
function ck($v,$m){global $checks;if(!$v)throw new RuntimeException('FAIL '.$m);$checks++;echo 'PASS '.$m.PHP_EOL;}
function api($o,$a=[],$t=''){global $s,$ip;return $s->dispatch($o,$a,$t?'Bearer '.$t:'',$ip);}
function q($sql,$a=[]){global $p;$r=$p->prepare($sql);$r->execute($a);$v=$r->fetchAll(PDO::FETCH_ASSOC);$r->closeCursor();return $v;}
function uid(){ $h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20); }
function deny($o,$a,$t,$code,$m){try{api($o,$a,$t);$ok=false;}catch(NativeError $e){$ok=$e->errorCode===$code;}ck($ok,$m);}
$prefix='delneg_'.bin2hex(random_bytes(5));$pw='password-'.bin2hex(random_bytes(12));
foreach(['x','y','z','r','f','t','cancel'] as $n){$ids[$n]=$container['userModel']->create(['username'=>$prefix.'_'.$n,'password'=>$pw,'role'=>'app-user']);$ss[$n]=api('auth.login',['username'=>$prefix.'_'.$n,'password'=>$pw,'deviceName'=>'Negative deletion']);}
function argsFor($session,$password){$preview=api('account.deletion.preview',[],$session['token']);return ['operationId'=>uid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$preview['previewHash'],'password'=>$password,'confirmation'=>'DELETE'];}
function child($operation,$params,$token){global $ip;$path='/tmp/delete-race-'.bin2hex(random_bytes(8)).'.json';file_put_contents($path,json_encode(['operation'=>$operation,'params'=>$params,'bearer'=>'Bearer '.$token,'ip'=>$ip.'-race']));chmod($path,0600);$proc=proc_open([PHP_BINARY,'/familyhub-tests/account-race-child.php',$path],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);stream_set_timeout($pipes[1],20);if(trim(fgets($pipes[1]))!=='ready'){throw new RuntimeException('Worker not ready');}return [$proc,$pipes,$path];}
function go($worker){fwrite($worker[1][0],"go\n");fflush($worker[1][0]);}
function done($worker){$v=json_decode(fgets($worker[1][1]),true,32,JSON_THROW_ON_ERROR);foreach($worker[1] as $pipe){fclose($pipe);}proc_close($worker[0]);unlink($worker[2]);return $v;}
// Unrelated scopes cannot cause false stale previews.
$op=argsFor($ss['x'],$pw);$scope=uid();api('scopes.create',['id'=>$scope,'kind'=>'project','name'=>'Unrelated','requestId'=>uid()],$ss['y']['token']);ck(api('account.deletion.confirm',$op,$ss['x']['token'])['deleted'],'unrelated scope creation does not stale deletion preview');
// Two live requests with the same operation ID: exactly one transaction deletes.
$op=argsFor($ss['z'],$pw);$w1=child('account.deletion.confirm',$op,$ss['z']['token']);$w2=child('account.deletion.confirm',$op,$ss['z']['token']);go($w1);go($w2);$r1=done($w1);$r2=done($w2);ck((int)$r1['ok']+(int)$r2['ok']===1,'concurrent confirms delete once');ck(($r1['error']??$r2['error']??'')==='device_revoked','other confirm cannot reuse old bearer');ck(api('account.deletion.status',['operationId'=>$op['operationId'],'receiptToken'=>$op['receiptToken']])['deleted'],'concurrent lost ACK recovered by receipt');
// Force user lock wait, revoke device before allowing request to proceed.
$op=argsFor($ss['r'],$pw);if($p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'){$p->exec('BEGIN IMMEDIATE');}else{$p->beginTransaction();q('SELECT id FROM users WHERE id=? FOR UPDATE',[$ids['r']]);}
$w=child('account.deletion.confirm',$op,$ss['r']['token']);go($w);usleep(250000);q('UPDATE familyhub_devices SET revoked_at=? WHERE id=?',[time(),$ss['r']['device']['id']]);if($p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'){$p->exec('COMMIT');}else{$p->commit();}$r=done($w);ck(!$r['ok']&&$r['error']==='device_revoked'&&count(q('SELECT id FROM users WHERE id=?',[$ids['r']]))===1,'revocation during lock wait stops deletion');
// SQL failure rolls back private data, receipt, file queue and user atomically.
$private=api('personal.ensure',[],$ss['f']['token'])['scope']['id'];$avatar='avatars/'.$ids['f'].'/'.bin2hex(random_bytes(10));$blob='rollback avatar';$container['objectStorage']->put($avatar,$blob);q('UPDATE users SET avatar_path=? WHERE id=?',[$avatar,$ids['f']]);$op=argsFor($ss['f'],$pw);$trigger='deletion_fail_'.bin2hex(random_bytes(5));$sql=$p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite' ? "CREATE TRIGGER $trigger BEFORE DELETE ON users WHEN OLD.id=".$ids['f']." BEGIN SELECT RAISE(ABORT,'synthetic-delete-failure'); END" : "CREATE TRIGGER $trigger BEFORE DELETE ON users FOR EACH ROW BEGIN IF OLD.id=".$ids['f']." THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic-delete-failure'; END IF; END";$p->exec($sql);
try{try{api('account.deletion.confirm',$op,$ss['f']['token']);$ok=false;}catch(PDOException $e){$ok=true;}ck($ok,'synthetic failure is surfaced');ck(count(q('SELECT id FROM users WHERE id=?',[$ids['f']]))===1&&count(q('SELECT id FROM familyhub_scopes WHERE id=?',[$private]))===1&&!q('SELECT operation_id FROM familyhub_deletion_receipts WHERE operation_id=?',[$op['operationId']]),'failed transaction preserves user/private data and no false receipt');ck(file_exists($container['objectStorage']->getSanitizedFilePath($avatar)),'SQL failure never removes avatar before commit');}finally{$p->exec('DROP TRIGGER '.$trigger);}ck(api('account.deletion.confirm',$op,$ss['f']['token'])['deleted'],'same unchanged request succeeds after transient SQL failure');
// Deterministic legacy child race: deletion must wait for parent lock, then
// see the committed foreign comment and block instead of cascading it away.
$pid=$container['projectModel']->create(['name'=>$prefix.'_legacy']);$tid=$container['taskCreationModel']->create(['title'=>'Legacy own task','project_id'=>$pid,'creator_id'=>$ids['y']]);$op=argsFor($ss['y'],$pw);$op['ownedScopeDeletions']=[$scope];
if($p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'){$p->exec('BEGIN IMMEDIATE');}else{$p->beginTransaction();q('SELECT id FROM tasks WHERE id=? FOR UPDATE',[$tid]);}$w=child('account.deletion.confirm',$op,$ss['y']['token']);go($w);usleep(250000);q('INSERT INTO comments(task_id,user_id,date_creation,comment) VALUES(?,?,?,?)',[$tid,$ids['r'],time(),'foreign comment during parent wait']);if($p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'){$p->exec('COMMIT');}else{$p->commit();}$r=done($w);ck(!$r['ok']&&$r['error']==='deletion_blocked'&&count(q('SELECT id FROM comments WHERE task_id=?',[$tid]))===1&&count(q('SELECT id FROM tasks WHERE id=?',[$tid]))===1,'foreign comment committed during parent lock wait survives and blocks deletion');
// Legacy anonymous author and subtask assignee are not proof of ownership.
q('DELETE FROM comments WHERE task_id=?',[$tid]);q('INSERT INTO comments(task_id,user_id,date_creation,comment) VALUES(?,0,?,?)',[$tid,time(),'unknown former author']);$plan=api('account.deletion.preview',[],$ss['y']['token']);ck(in_array('legacy_task_has_other_contributions',array_column($plan['blockers'],'code')),'anonymous legacy comment remains protected as unresolved author');q('DELETE FROM comments WHERE task_id=?',[$tid]);q('INSERT INTO subtasks(task_id,title,user_id) VALUES(?,?,?)',[$tid,'unknown author subtask',$ids['y']]);$plan=api('account.deletion.preview',[],$ss['y']['token']);ck(in_array('legacy_task_has_other_contributions',array_column($plan['blockers'],'code')),'subtask assigned to deleting account is not treated as authored by that account');
// Real TOTP configured after initial login; issue fresh session with login code.
$secret=\Otp\GoogleAuthenticator::generateRandom();q('UPDATE users SET twofactor_activated=1,twofactor_secret=? WHERE id=?',[$secret,$ids['t']]);$step=intdiv(time(),30);$otp=(new \Otp\Otp())->totp(\Base32\Base32::decode($secret),$step);$totp=api('auth.login',['username'=>$prefix.'_t','password'=>$pw,'deviceName'=>'2FA deletion','otp'=>$otp]);$op=argsFor($totp,$pw);deny('account.deletion.confirm',$op,$totp['token'],'two_factor_required','deletion requires enabled second factor');$op['otp']=$otp;deny('account.deletion.confirm',$op,$totp['token'],'invalid_credentials','login TOTP cannot be replayed for deletion');$op['otp']=(new \Otp\Otp())->totp(\Base32\Base32::decode($secret),$step+1);ck(api('account.deletion.confirm',$op,$totp['token'])['deleted'],'fresh TOTP confirms deletion');
// Cancellation is a terminal receipt under the same deletion mutex.
$op=argsFor($ss['cancel'],$pw);$receipt=['operationId'=>$op['operationId'],'receiptToken'=>$op['receiptToken']];$w=child('account.deletion.confirm',$op,$ss['cancel']['token']);deny('account.deletion.cancelPending',$receipt,'','auth_required','unknown cancellation requires active account before marker insertion');$cancelled=api('account.deletion.cancelPending',$receipt,$ss['cancel']['token']);go($w);$late=done($w);ck($cancelled['cancelled']&&!$cancelled['deleted']&&!$cancelled['cleanupPending'],'cancel-first writes terminal receipt without falsely deleting');ck(!$late['ok']&&$late['error']==='deletion_cancelled'&&count(q('SELECT id FROM users WHERE id=?',[$ids['cancel']]))===1,'late original request after cancellation cannot delete');ck(api('account.deletion.status',$receipt)['cancelled'],'cancelled result is recoverable without bearer');$wrong=$receipt;$wrong['receiptToken']=bin2hex(random_bytes(32));deny('account.deletion.cancelPending',$wrong,'','idempotency_mismatch','wrong cancel token cannot overwrite terminal receipt');ck(!api('account.deletion.status',$wrong)['cancelled'],'wrong receipt discloses no cancellation');$next=argsFor($ss['cancel'],$pw);ck(api('account.deletion.confirm',$next,$ss['cancel']['token'])['deleted'],'confirmed cancellation permits new operation after fresh review');$result=api('account.deletion.cancelPending',['operationId'=>$next['operationId'],'receiptToken'=>$next['receiptToken']]);ck($result['deleted']&&!$result['cancelled'],'original-first cancellation returns actual deleted receipt');
// Managed/unspecified mode cannot advertise or execute deletion.
$path='/tmp/delete-mode-'.bin2hex(random_bytes(6)).'.php';file_put_contents($path,"<?php error_reporting(0); define('FAMILYHUB_ACCOUNT_MODE','managed');require '/var/www/app/app/common.php';if(session_status()===PHP_SESSION_ACTIVE){session_abort();}\$s=new \\Kanboard\\Plugin\\FamilyHub\\Model\\NativeService(\$container);echo json_encode(\$s->dispatch('capabilities',[],'','managed-test')['features']['accountDeletion']);try{\$s->dispatch('account.deletion.status',['operationId'=>'".uid()."','receiptToken'=>'".bin2hex(random_bytes(32))."'],'','managed-test');}catch(\\Kanboard\\Plugin\\FamilyHub\\Model\\NativeError \$e){echo ':'.\$e->errorCode;}");$proc=proc_open([PHP_BINARY,$path],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);$out=stream_get_contents($pipes[1]);foreach($pipes as $pipe){fclose($pipe);}proc_close($proc);unlink($path);ck($out==='false:feature_disabled','managed server rejects deletion independently of client');
echo 'SUCCESS '.$checks.' negative/race deletion checks ('.$p->getAttribute(PDO::ATTR_DRIVER_NAME).')'.PHP_EOL;
