<?php
umask(0077);
$port=random_int(30000,40000);
define('FAMILYHUB_ACCOUNT_MAIL_KEY_BASE64',base64_encode(random_bytes(32)));
define('FAMILYHUB_SMTP_HOST','127.0.0.1');define('FAMILYHUB_SMTP_PORT',$port);define('FAMILYHUB_SMTP_ENCRYPTION','none');define('FAMILYHUB_SMTP_ALLOW_LOCAL_PLAINTEXT',true);define('FAMILYHUB_SMTP_FROM','sender@capture.invalid');define('FAMILYHUB_PUBLIC_URL','http://127.0.0.1:18380');define('MAIL_BCC',['forbidden@capture.invalid']);
require '/var/www/app/app/common.php';if(session_status()===PHP_SESSION_ACTIVE){session_abort();}
if(!defined('FAMILYHUB_DEVELOPMENT_MODE')||FAMILYHUB_DEVELOPMENT_MODE!==true){throw new RuntimeException('Synthetic only');}
use Kanboard\Plugin\FamilyHub\Model\NativeService;
use Kanboard\Plugin\FamilyHub\Model\NativeError;
use Kanboard\Plugin\FamilyHub\Model\NativeAccountMailCrypto;
use Kanboard\Plugin\FamilyHub\Model\NativeAccountMailQueue;
use Kanboard\Plugin\FamilyHub\Model\NativeInvitationMailQueue;
$pdo=$container['db']->getConnection();$service=new NativeService($container);$checks=0;$prefix='email_'.bin2hex(random_bytes(5));$ip='email-test-'.bin2hex(random_bytes(8));$password=bin2hex(random_bytes(16));
function check($v,$m){global$checks;if(!$v){throw new RuntimeException('FAIL: '.$m);}$checks++;echo 'PASS: '.$m.PHP_EOL;}
function q($s,$p=[]){global$pdo;$q=$pdo->prepare($s);$q->execute($p);$r=$q->fetchAll(PDO::FETCH_ASSOC);$q->closeCursor();return$r;}
function api($op,$p=[],$token=''){global$service,$ip;return$service->dispatch($op,$p,$token?'Bearer '.$token:'',$ip);}
function deny($op,$p,$token,$code,$status=null){try{api($op,$p,$token);$ok=false;}catch(NativeError$e){$ok=$e->errorCode===$code&&($status===null||$e->status===$status);}check($ok,$op.' denies '.$code);}
function uuid(){ $h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20); }
function user($suffix,$email=null,$verified=false){global$container,$prefix,$password;$id=$container['userModel']->create(['username'=>$prefix.'_'.$suffix,'password'=>$password,'email'=>$email??'','role'=>'app-user']);$session=api('auth.login',['username'=>$prefix.'_'.$suffix,'password'=>$password,'deviceName'=>'Email test']);if($verified){q('INSERT INTO familyhub_email_identities(account_id,email,verified_at,revision) VALUES(?,?,?,1)',[$session['user']['accountId'],$email,time()]);}return$session;}
function invite($email,$token=null){global$scope,$owner;return api('invitations2.create',['scopeId'=>$scope['id'],'recipientEmail'=>$email,'role'=>'member','requestId'=>uuid(),'language'=>'sl'],$token??$owner['token']);}
function secret($invitation){global$container;$job=q('SELECT * FROM familyhub_invitation_mail WHERE invitation_id=?',[$invitation['id']])[0];return NativeAccountMailCrypto::decrypt($job['token_cipher'],(new NativeInvitationMailQueue($container))->aad($invitation['id']));}
function binding($inv){return q('SELECT recipient_account_id FROM familyhub_invitations WHERE id=?',[$inv['id']])[0]['recipient_account_id'];}
function race($requests){$children=[];$paths=[];try{foreach($requests as$r){$r['mailKey']=FAMILYHUB_ACCOUNT_MAIL_KEY_BASE64;$r['ip']='email-race-'.bin2hex(random_bytes(8));$path='/tmp/email-race-'.bin2hex(random_bytes(8)).'.json';file_put_contents($path,json_encode($r));$paths[]=$path;$proc=proc_open([PHP_BINARY,'/familyhub-tests/account-race-child.php',$path],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);stream_set_timeout($pipes[1],20);if(trim(fgets($pipes[1]))!=='ready'){throw new RuntimeException('Race unavailable');}$children[]=[$proc,$pipes];}foreach($children as[$proc,$pipes]){fwrite($pipes[0],"go\n");fflush($pipes[0]);}$out=[];foreach($children as[$proc,$pipes]){$out[]=json_decode(fgets($pipes[1]),true,32,JSON_THROW_ON_ERROR);foreach($pipes as$p){fclose($p);}proc_close($proc);}return$out;}finally{foreach($paths as$p){@unlink($p);}}}
$owner=user('owner');$wrong=user('wrong',$prefix.'wrong@capture.invalid',true);$existingEmail=$prefix.'existing@capture.invalid';$existing=user('existing',$existingEmail,true);$scope=api('scopes.create',['id'=>uuid(),'kind'=>'household','name'=>'Invitation household','requestId'=>uuid()],$owner['token'])['scope'];
$cap=api('capabilities');check($cap['features']['emailInvitations']&&$cap['invitationContractVersions']===[1,2,3],'versioned email capability additive');
$request=['scopeId'=>$scope['id'],'recipientEmail'=>strtoupper($existingEmail),'role'=>'member','requestId'=>uuid(),'language'=>'sl'];$created=api('invitations2.create',$request,$owner['token']);$inv=$created['invitation'];$token=secret($inv);
check($created['deliveryQueued']&&!isset($created['token'])&&$inv['recipientEmail']===$existingEmail&&$inv['contractVersion']===2,'create normalizes address and returns queued without token');check(binding($inv)===$existing['user']['accountId'],'existing verified email bound to durable account');check(api('invitations2.create',$request,$owner['token'])===$created,'lost create response replay identical and no second mail');check(count(q('SELECT invitation_id FROM familyhub_invitation_mail WHERE invitation_id=?',[$inv['id']]))===1,'one durable encrypted mail job');$changed=$request;$changed['role']='viewer';deny('invitations2.create',$changed,$owner['token'],'idempotency_mismatch');check(!str_contains(json_encode(q('SELECT * FROM familyhub_invitations WHERE id=?',[$inv['id']])),$token),'invitation stores token hash only');check(!str_contains(json_encode(api('invitations.list',['scopeId'=>$scope['id']],$owner['token'])),$token),'sender list never exposes registration token');
$preview=api('invitations2.preview',['token'=>$token]);check($preview['registrationAllowed']&&$preview['requiresExplicitAcceptance']&&$preview['inviterName']===$owner['user']['username']&&$preview['scope']['id']===$scope['id'],'token preview shows inviter, role and space without account enumeration');
$registration=['token'=>$token,'username'=>$prefix.'_new','password'=>$password,'displayName'=>'New recipient','deviceName'=>'Invited device'];deny('auth.registerInvitation2',$registration,'','invitation_authentication_required');deny('invitations2.accept',['token'=>$token],$wrong['token'],'invitation_invalid',403);check(api('invitations2.pending',[],$wrong['token'])['invitations']===[],'wrong account pending inbox empty');$pending=api('invitations2.pending',[],$existing['token'])['invitations'];check(count($pending)===1&&!str_contains(json_encode($pending),$token),'verified recipient inbox contains invitation without secret');check(api('scopes.list',[],$existing['token'])['scopes']===[],'pending invitation grants no membership');
$accept=['operation'=>'invitations2.accept','params'=>['invitationId'=>$inv['id']],'bearer'=>'Bearer '.$existing['token']];$out=race([$accept,$accept]);check($out[0]['ok']&&$out[1]['ok']&&$out[0]['scopeId']===$scope['id']&&$out[1]['scopeId']===$scope['id'],'simultaneous accept returns same scope once');check(count(q('SELECT * FROM familyhub_members WHERE scope_id=? AND account_id=?',[$scope['id'],$existing['user']['accountId']]))===1,'accept creates one membership');check(api('invitations2.accept',['token'=>$token],$existing['token'])['scope']['id']===$scope['id'],'lost acceptance response safe retry token');check(api('invitations2.pending',[],$existing['token'])['invitations']===[],'accepted invitation removed from pending');
check(api('invitations2.preview',['token'=>$token],$existing['token'])['scope']['id']===$scope['id'],'authenticated accepted preview recovers lost response');
deny('invitations2.preview',['token'=>$token],'','invitation_invalid');deny('invitations2.preview',['token'=>$token],$wrong['token'],'invitation_invalid',403);
q('UPDATE familyhub_members SET active=0 WHERE scope_id=? AND account_id=?',[$scope['id'],$existing['user']['accountId']]);deny('invitations2.accept',['token'=>$token],$existing['token'],'permission_revoked');deny('invitations2.preview',['token'=>$token],$existing['token'],'permission_revoked');q('UPDATE familyhub_members SET active=1 WHERE scope_id=? AND account_id=?',[$scope['id'],$existing['user']['accountId']]);
$newEmail=$prefix.'new@capture.invalid';$newInv=invite($newEmail)['invitation'];$newToken=secret($newInv);$newReg=$registration;$newReg['token']=$newToken;$newReg['username']=$prefix.'_registered';$out=race([['operation'=>'auth.registerInvitation2','params'=>$newReg],['operation'=>'auth.registerInvitation2','params'=>$newReg]]);check(count(array_filter($out,fn($r)=>$r['ok']))===1&&count(array_filter($out,fn($r)=>($r['error']??'')==='invitation_authentication_required'))===1,'concurrent registration creates exactly one account');$new=api('auth.login',['username'=>$newReg['username'],'password'=>$password,'deviceName'=>'Recovered lost registration']);check(api('account.status',[],$new['token'])['emailVerified'],'invitation possession verifies new account email');check(api('scopes.list',[],$new['token'])['scopes']===[],'registration lost response recovery still grants no membership');check(count(api('invitations2.pending',[],$new['token'])['invitations'])===1,'registration retains pending invitation across new login');check(api('invitations2.accept',['token'=>$newToken],$new['token'])['scope']['id']===$scope['id'],'new account explicitly accepts afterward');
$unverifiedEmail=$prefix.'unverified@capture.invalid';$unverified=user('unverified',$unverifiedEmail);q('INSERT INTO familyhub_email_identities(account_id,pending_email,revision) VALUES(?,?,1)',[$unverified['user']['accountId'],$unverifiedEmail]);$unInv=invite($unverifiedEmail)['invitation'];$unToken=secret($unInv);check(binding($unInv)===null,'core and pending email never bind invitation');deny('invitations2.accept',['token'=>$unToken],$unverified['token'],'invitation_invalid',403);check(api('invitations2.pending',[],$unverified['token'])['invitations']===[],'unverified inbox remains empty');$unReg=$registration;$unReg['token']=$unToken;$unReg['username']=$prefix.'_verifiednew';$unNew=api('auth.registerInvitation2',$unReg);check($unNew['user']['accountId']!==$unverified['user']['accountId'],'unverified existing user cannot reserve address against invited new account');
$dupEmail=$prefix.'duplicate@capture.invalid';$dupA=user('dup_a',$dupEmail,true);$dupB=user('dup_b',$dupEmail,true);$dup=invite($dupEmail)['invitation'];$dupToken=secret($dup);deny('invitations2.accept',['token'=>$dupToken],$dupA['token'],'invitation_invalid',403);deny('invitations2.accept',['token'=>$dupToken],$dupB['token'],'invitation_invalid',403);$dupReg=$registration;$dupReg['token']=$dupToken;deny('auth.registerInvitation2',$dupReg,'','invitation_authentication_required');q('UPDATE familyhub_email_identities SET email=? WHERE account_id=?',[$prefix.'other@capture.invalid',$dupB['user']['accountId']]);deny('invitations2.accept',['token'=>$dupToken],$dupA['token'],'invitation_invalid',403);check(api('invitations2.pending',[],$dupA['token'])['invitations']===[],'historical duplicate invite remains permanently blocked');
$changeInv=invite($existingEmail)['invitation'];$changeToken=secret($changeInv);q('UPDATE familyhub_email_identities SET email=?,revision=revision+1 WHERE account_id=?',[$prefix.'changed@capture.invalid',$existing['user']['accountId']]);deny('invitations2.accept',['token'=>$changeToken],$existing['token'],'invitation_invalid',403);$replacement=user('replacement',$existingEmail,true);deny('invitations2.accept',['token'=>$changeToken],$replacement['token'],'invitation_invalid',403);check(api('invitations2.pending',[],$replacement['token'])['invitations']===[],'email reassignment cannot inherit previously bound invitation');
$rev=invite($prefix.'revoke@capture.invalid')['invitation'];$revToken=secret($rev);api('invitations.revoke',['scopeId'=>$scope['id'],'invitationId'=>$rev['id'],'requestId'=>uuid()],$owner['token']);deny('invitations2.preview',['token'=>$revToken],'','invitation_invalid');$revReg=$registration;$revReg['token']=$revToken;deny('auth.registerInvitation2',$revReg,'','invitation_invalid');check(q('SELECT token_cipher FROM familyhub_invitation_mail WHERE invitation_id=?',[$rev['id']])[0]['token_cipher']===null,'revocation immediately clears queued secret');
$expired=invite($prefix.'expired@capture.invalid')['invitation'];$expiredToken=secret($expired);q('UPDATE familyhub_invitations SET expires_at=0 WHERE id=?',[$expired['id']]);deny('invitations2.preview',['token'=>$expiredToken],'','invitation_invalid');$expReg=$registration;$expReg['token']=$expiredToken;deny('auth.registerInvitation2',$expReg,'','invitation_invalid');
// Existing v1 contract refuses v2 tokens and still grants on its legacy register path.
deny('auth.register',$newReg,'','invitation_invalid');deny('invitations.accept',['token'=>$unToken],$unNew['token'],'invitation_invalid');$legacy=api('invitations.create',['scopeId'=>$scope['id'],'recipientUsername'=>$prefix.'_legacy','role'=>'viewer','requestId'=>uuid()],$owner['token']);$legacyReg=$registration;$legacyReg['token']=$legacy['token'];$legacyReg['username']=$prefix.'_legacy';$legacySession=api('auth.register',$legacyReg);check(count(api('scopes.list',[],$legacySession['token'])['scopes'])===1,'legacy username registration semantics preserved');deny('invitations2.preview',['token'=>$legacy['token']],'','invitation_invalid');
// Capture actual SMTP only to a loopback test sink, never real addresses.
$delivery=invite($prefix.'delivery@capture.invalid')['invitation'];$deliveryToken=secret($delivery);$output='/tmp/familyhub-smtp-email-'.bin2hex(random_bytes(8)).'.json';$process=proc_open([PHP_BINARY,'/familyhub-tests/smtp-capture.php',$output,(string)$port],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);stream_set_timeout($pipes[1],5);if(trim(fgets($pipes[1]))!=='ready'){throw new RuntimeException('Capture unavailable');}
try {
// Isolate this job from synthetic earlier recipients without modifying their invitations.
q('UPDATE familyhub_invitation_mail SET next_attempt=? WHERE state=\'pending\' AND invitation_id<>?',[time()+3600,$delivery['id']]);
$result=(new NativeAccountMailQueue($container))->run(20);check($result['accepted']===1,'existing security-mail worker delivers email invitation via SMTP');$messages=json_decode(file_get_contents($output),true)['messages'];$body=quoted_printable_decode($messages[0]['body']);check($messages[0]['recipients']===[$prefix.'delivery@capture.invalid']&&!str_contains($body,'forbidden@'),'SMTP invitation excludes global BCC and sends only recipient');check(str_contains($body,'#token='.$deliveryToken)&&str_contains($body,'Invitation household'),'SMTP body contains landing fragment and invited space');check(!str_contains(explode('#token=',$body)[0],$deliveryToken),'token not sent in URL query');check(q('SELECT token_cipher FROM familyhub_invitation_mail WHERE invitation_id=?',[$delivery['id']])[0]['token_cipher']===null,'successful SMTP clears encrypted queued secret');check((new NativeAccountMailQueue($container))->run(20)['accepted']===0,'worker retry never resends accepted invitation');check(q('SELECT token_cipher FROM familyhub_invitation_mail WHERE invitation_id=?',[$expired['id']])[0]['token_cipher']===null,'cron expires pending encrypted secrets');
} finally {proc_terminate($process);foreach($pipes as$p){if(is_resource($p)){fclose($p);}}proc_close($process);@unlink($output);}
// Queue rechecks scope/issuer ACL, retries bounded SMTP failure, and recovers lease.
$fake=new class{public function send($a,$b,$c,$d,$e,$f=[]){return ['accepted'=>true];}};
$archive=invite($prefix.'archive@capture.invalid')['invitation'];q('UPDATE familyhub_scopes SET archived=1 WHERE id=?',[$scope['id']]);$archiveReg=$registration;$archiveReg['token']=secret($archive);deny('auth.registerInvitation2',$archiveReg,'','scope_archived');check((new NativeInvitationMailQueue($container))->run(20,$fake)['cancelled']===1,'archived scope cancels invitation before SMTP');q('UPDATE familyhub_scopes SET archived=0 WHERE id=?',[$scope['id']]);
$retry=invite($prefix.'retry@capture.invalid')['invitation'];$reject=new class{public function send($a,$b,$c,$d,$e,$f=[]){throw new RuntimeException('Synthetic SMTP failure');}};check((new NativeInvitationMailQueue($container))->run(20,$reject)['retry']===1,'SMTP rejection retries durably');$job=q('SELECT * FROM familyhub_invitation_mail WHERE invitation_id=?',[$retry['id']])[0];check($job['state']==='pending'&&(int)$job['next_attempt']>time()&&$job['token_cipher']!==null,'retry preserves cipher with delayed attempt');q('UPDATE familyhub_invitation_mail SET state=\'processing\',lease_token=\'test\',lease_until=? WHERE invitation_id=?',[time()+120,$retry['id']]);check((new NativeInvitationMailQueue($container))->run(20,$fake)['examined']===0,'active worker lease excludes competition');q('UPDATE familyhub_invitation_mail SET lease_until=0 WHERE invitation_id=?',[$retry['id']]);check((new NativeInvitationMailQueue($container))->run(20,$fake)['accepted']===1,'expired SMTP lease recovers');
$issuer=invite($prefix.'issuer@capture.invalid')['invitation'];q('UPDATE familyhub_members SET active=0 WHERE scope_id=? AND account_id=?',[$scope['id'],$owner['user']['accountId']]);check((new NativeInvitationMailQueue($container))->run(20,$fake)['cancelled']===1,'issuer loses owner rights and mail cancels');q('UPDATE familyhub_members SET active=1 WHERE scope_id=? AND account_id=?',[$scope['id'],$owner['user']['accountId']]);
// Real confirm/register race cannot create two verified identities for one address.
$verifyUser=user('verifyrace');$raceEmail=$prefix.'race@capture.invalid';api('account.email.request',['email'=>$raceEmail,'language'=>'sl','password'=>$password],$verifyUser['token']);$row=q('SELECT * FROM familyhub_account_tokens WHERE account_id=? AND purpose=\'verify\' AND revoked_at IS NULL',[$verifyUser['user']['accountId']])[0];$cipher=q('SELECT token_cipher FROM familyhub_account_mail WHERE token_id=?',[$row['id']])[0]['token_cipher'];$verifyCode=NativeAccountMailCrypto::decrypt($cipher,(new \Kanboard\Plugin\FamilyHub\Model\NativeAccountTokens($container))->aad($row['id'],$row['account_id']));$raceInv=invite($raceEmail)['invitation'];$raceReg=$registration;$raceReg['token']=secret($raceInv);$raceReg['username']=$prefix.'_racer';$out=race([['operation'=>'auth.registerInvitation2','params'=>$raceReg],['operation'=>'account.email.confirm','params'=>['token'=>$verifyCode],'bearer'=>'Bearer '.$verifyUser['token']]]);check(count(array_filter($out,fn($r)=>$r['ok']))===1,'email confirm and registration serialize exactly one winner');check(count(q('SELECT account_id FROM familyhub_email_identities WHERE email=? AND verified_at IS NOT NULL',[$raceEmail]))===1,'confirm/register race keeps single verified identity');
// Recipient quotas are durable and opaque; no account lookup endpoint exists.
$quotaEmail=$prefix.'quota@capture.invalid';for($n=0;$n<5;$n++){invite($quotaEmail);}deny('invitations2.create',['scopeId'=>$scope['id'],'recipientEmail'=>$quotaEmail,'role'=>'member','requestId'=>uuid(),'language'=>'sl'],$owner['token'],'rate_limited');
// Another synthetic owner isolates quota accounting for deletion/recreate tests.
$owner=user('owner2');$scope=api('scopes.create',['id'=>uuid(),'kind'=>'household','name'=>'Deletion invitation household','requestId'=>uuid()],$owner['token'])['scope'];
$deletionEmail=$prefix.'deletion@capture.invalid';$first=invite($deletionEmail)['invitation'];$second=invite($deletionEmail)['invitation'];$firstToken=secret($first);$secondToken=secret($second);$delReg=$registration;$delReg['token']=$firstToken;$delReg['username']=$prefix.'_deleter';$deleter=api('auth.registerInvitation2',$delReg);
check(binding($first)===$deleter['user']['accountId']&&binding($second)===$deleter['user']['accountId'],'registration binds every unbound same-address invitation');
$plan=api('account.deletion.preview',[],$deleter['token']);$result=api('account.deletion.confirm',['operationId'=>uuid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$plan['previewHash'],'password'=>$password,'confirmation'=>'DELETE'],$deleter['token']);check($result['deleted'],'invited account can actually delete through account policy');
check(!q('SELECT id FROM familyhub_invitations WHERE id IN (?,?)',[$first['id'],$second['id']])&&!q('SELECT invitation_id FROM familyhub_invitation_mail WHERE invitation_id IN (?,?)',[$first['id'],$second['id']]),'account deletion removes all bound invitations and cascading encrypted mail');
$recreated=user('recreated',$deletionEmail,true);deny('invitations2.accept',['token'=>$secondToken],$recreated['token'],'invitation_invalid');$delReg['token']=$secondToken;deny('auth.registerInvitation2',$delReg,'','invitation_invalid');
$confirmEmail=$prefix.'confirmbinding@capture.invalid';$preConfirm=invite($confirmEmail)['invitation'];$confirmUser=user('confirmbinding');api('account.email.request',['email'=>$confirmEmail,'language'=>'sl','password'=>$password],$confirmUser['token']);$vr=q('SELECT * FROM familyhub_account_tokens WHERE account_id=? AND purpose=\'verify\' AND revoked_at IS NULL',[$confirmUser['user']['accountId']])[0];$vc=q('SELECT token_cipher FROM familyhub_account_mail WHERE token_id=?',[$vr['id']])[0]['token_cipher'];$verifyToken=NativeAccountMailCrypto::decrypt($vc,(new \Kanboard\Plugin\FamilyHub\Model\NativeAccountTokens($container))->aad($vr['id'],$vr['account_id']));api('account.email.confirm',['token'=>$verifyToken],$confirmUser['token']);check(binding($preConfirm)===$confirmUser['user']['accountId'],'email confirmation binds pre-existing unbound invitation');
$rateId=hash('sha256','invite-sender:'.$owner['user']['accountId']);$attempts=(int)q('SELECT attempts FROM familyhub_rate_limits WHERE id=?',[$rateId])[0]['attempts'];for($n=$attempts;$n<30;$n++){invite($prefix.'senderquota'.$n.'@capture.invalid');}deny('invitations2.create',['scopeId'=>$scope['id'],'recipientEmail'=>$prefix.'senderquota-final@capture.invalid','role'=>'member','requestId'=>uuid(),'language'=>'sl'],$owner['token'],'rate_limited');
// A third owner avoids consuming the exhausted synthetic sender bucket.
$owner=user('owner3');$scope=api('scopes.create',['id'=>uuid(),'kind'=>'household','name'=>'SMTP revoke race','requestId'=>uuid()],$owner['token'])['scope'];$raceMail=invite($prefix.'mailrace@capture.invalid')['invitation'];q('UPDATE familyhub_invitation_mail SET next_attempt=? WHERE state=\'pending\' AND invitation_id<>?',[time()+3600,$raceMail['id']]);$out=race([['operation'=>'test.invitationMail','params'=>[]],['operation'=>'invitations.revoke','params'=>['scopeId'=>$scope['id'],'invitationId'=>$raceMail['id'],'requestId'=>uuid()],'bearer'=>'Bearer '.$owner['token']]]);check($out[0]['ok']&&$out[1]['ok'],'SMTP and revoke race both finish without deadlock');$job=q('SELECT * FROM familyhub_invitation_mail WHERE invitation_id=?',[$raceMail['id']])[0];check($job['token_cipher']===null&&in_array($job['state'],['accepted','cancelled'],true),'SMTP/revoke race leaves no queued secret or resend');check((new NativeInvitationMailQueue($container))->run(20,$fake)['accepted']===0,'revoked raced invitation is never resent');
// Leave all retained synthetic fixture jobs inert; no production rows affected.
q('UPDATE familyhub_invitation_mail SET state=\'cancelled\',token_cipher=NULL,lease_token=NULL WHERE invitation_id IN (SELECT i.id FROM familyhub_invitations i JOIN users u ON u.id=i.creator_id WHERE u.username LIKE ?) AND state<>\'accepted\'',[$prefix.'%']);q('UPDATE familyhub_account_tokens SET revoked_at=? WHERE account_id IN (SELECT a.account_id FROM familyhub_accounts a JOIN users u ON u.id=a.user_id WHERE u.username LIKE ?) AND consumed_at IS NULL AND revoked_at IS NULL',[time(),$prefix.'%']);q('UPDATE familyhub_account_mail SET state=\'cancelled\',token_cipher=NULL,lease_token=NULL WHERE token_id IN (SELECT t.id FROM familyhub_account_tokens t JOIN familyhub_accounts a ON a.account_id=t.account_id JOIN users u ON u.id=a.user_id WHERE u.username LIKE ?) AND state<>\'accepted\'',[$prefix.'%']);
check((int)q('SELECT version FROM plugin_schema_versions WHERE plugin=\'familyhub\'')[0]['version']===15,'additive schema15 migrated');
echo 'SUCCESS '.$checks.' email invitation checks ('.$pdo->getAttribute(PDO::ATTR_DRIVER_NAME).', local SMTP only)'.PHP_EOL;
