<?php
require '/var/www/app/app/common.php';
if (!defined('FAMILYHUB_DEVELOPMENT_MODE') || FAMILYHUB_DEVELOPMENT_MODE !== true) { throw new RuntimeException('Development only'); }
$checks=0;$prefix='finance_'.bin2hex(random_bytes(4));$password=bin2hex(random_bytes(14));$pdo=$container['db']->getConnection();$sqlite=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite';
foreach(['login-ip:','scopes-ip:','invitation-ip:','finance-ip:','inbox-ip:','sync-ip:'] as $key){$pdo->prepare('DELETE FROM familyhub_rate_limits WHERE id=?')->execute([hash('sha256',$key.'127.0.0.1')]);}
function uuid(){$h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20);}
function check($ok,$message){global$checks;if(!$ok){throw new RuntimeException('FAIL: '.$message);}$checks++;echo 'PASS: '.$message.PHP_EOL;}
function handle($op,$params=[],$token=null){$ch=curl_init('http://127.0.0.1/index.php?controller=NativeApiController&action=handle&plugin=FamilyHub');$h=['Content-Type: application/json'];if($token){$h[]='Authorization: Bearer '.$token;}curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>$h,CURLOPT_POSTFIELDS=>json_encode(['v'=>1,'op'=>$op,'params'=>(object)$params])]);return $ch;}
function call($op,$params=[],$token=null){$ch=handle($op,$params,$token);$raw=curl_exec($ch);$r=['status'=>curl_getinfo($ch,CURLINFO_HTTP_CODE),'body'=>json_decode($raw,true)];curl_close($ch);return$r;}
function data($r){if($r['status']!==200){throw new RuntimeException('Unexpected HTTP '.$r['status'].' '.($r['body']['error']['code']??'invalid'));}return$r['body']['data'];}
function err($r,$c,$s){return$r['status']===$s&&($r['body']['error']['code']??null)===$c;}
function push($s,$id,$type,$p,$r=0,$op=null,$deleted=false){return['scopeId'=>$s,'operation'=>['opId'=>$op??uuid(),'recordId'=>$id,'type'=>$type,'expectedRevision'=>$r,'deleted'=>$deleted,'payload'=>$p]];}
function parallel($requests){$m=curl_multi_init();$hs=[];foreach($requests as[$op,$p,$t]){$h=handle($op,$p,$t);$hs[]=$h;curl_multi_add_handle($m,$h);}do{curl_multi_exec($m,$running);if($running){curl_multi_select($m,0.1);}}while($running);$out=[];foreach($hs as$h){$out[]=['status'=>curl_getinfo($h,CURLINFO_HTTP_CODE),'body'=>json_decode(curl_multi_getcontent($h),true)];curl_multi_remove_handle($m,$h);curl_close($h);}curl_multi_close($m);return$out;}
$sessions=[];$users=[];foreach(['owner','member','viewer','foreign']as$role){$users[$role]=$container['userModel']->create(['username'=>$prefix.'_'.$role,'password'=>$password,'role'=>'app-user']);$sessions[$role]=data(call('auth.login',['username'=>$prefix.'_'.$role,'password'=>$password,'deviceName'=>'Synthetic finance']));}
$o=$sessions['owner']['token'];$m=$sessions['member']['token'];$v=$sessions['viewer']['token'];$f=$sessions['foreign']['token'];$scope=uuid();data(call('scopes.create',['id'=>$scope,'kind'=>'household','name'=>'Finance test','requestId'=>uuid()],$o));foreach(['member','viewer']as$role){$inv=data(call('invitations.create',['scopeId'=>$scope,'recipientUsername'=>$prefix.'_'.$role,'role'=>$role==='viewer'?'viewer':'member','requestId'=>uuid()],$o));data(call('invitations.accept',['token'=>$inv['token']],$sessions[$role]['token']));}
check(!data(call('finance.policy',['scopeId'=>$scope],$m))['enabled'],'finance disabled until explicit owner enable');
check(err(call('finance.enable',['scopeId'=>$scope,'enabled'=>true,'requestId'=>uuid()],$m),'permission_revoked',403),'member cannot enable shared finance');
$enable=['scopeId'=>$scope,'enabled'=>true,'requestId'=>uuid()];$policy=data(call('finance.enable',$enable,$o));check($policy['enabled']&&$policy['grant']==='write','explicit enable grants only owner write');
check(data(call('finance.enable',$enable,$o))===$policy,'finance enable idempotent');
check(data(call('finance.policy',['scopeId'=>$scope],$m))['grant']==='none','membership does not imply finance read');
$deny=call('finance.pull',['scopeId'=>$scope,'cursor'=>0],$m);check(err($deny,'finance_forbidden',403)&&$deny['body']['error']['details']===[],'unauthorized finance error has no record details');
check(err(call('finance.grant',['scopeId'=>$scope,'accountId'=>$sessions['viewer']['user']['accountId'],'grant'=>'write','requestId'=>uuid()],$o),'invalid_finance_grant',422),'viewer cannot receive financial write');
foreach([['member','write'],['viewer','read']]as[$who,$level]){data(call('finance.grant',['scopeId'=>$scope,'accountId'=>$sessions[$who]['user']['accountId'],'grant'=>$level,'requestId'=>uuid()],$o));}
$now=gmdate('Y-m-d\TH:i:s\Z');$a=uuid();$b=uuid();$account=['name'=>'Member shared account','currency'=>'EUR','openingBalanceMinor'=>10000,'ownerAccountId'=>$sessions['member']['user']['accountId'],'createdAt'=>$now,'updatedAt'=>$now];
$ac=push($scope,$a,'financeAccount',$account);$ack=data(call('finance.push',$ac,$o));check($ack['record']['createdByAccountId']===$sessions['owner']['user']['accountId']&&$ack['record']['payload']['ownerAccountId']===$sessions['member']['user']['accountId'],'financial author differs from account holder');
$account2=array_replace($account,['name'=>'Household shared account','openingBalanceMinor'=>0,'ownerAccountId'=>null]);data(call('finance.push',push($scope,$b,'financeAccount',$account2),$o));
check(err(call('finance.push',push($scope,uuid(),'financeAccount',array_replace($account,['currency'=>'JPY'])),$o),'unsupported_currency',422),'unsupported minor-unit currency rejected');
check(err(call('finance.push',push($scope,$a,'financeAccount',array_replace($account,['openingBalanceMinor'=>20000]),1),$o),'opening_balance_immutable',422),'opening balance cannot silently overwrite history');
$entry=uuid();$p=['accountId'=>$b,'kind'=>'expense','status'=>'posted','amountMinor'=>1234,'currency'=>'EUR','title'=>'Shared bill','notes'=>'','category'=>'home','payerAccountId'=>$sessions['member']['user']['accountId'],'recipientAccountId'=>null,'occurredAt'=>$now,'createdAt'=>$now,'updatedAt'=>$now];
$ep=push($scope,$entry,'financeEntry',$p);$eack=data(call('finance.push',$ep,$o));check($eack['record']['payload']['payerAccountId']!==$eack['record']['createdByAccountId'],'payer distinct from canonical entry creator');
check(err(call('finance.push',push($scope,uuid(),'financeEntry',array_replace($p,['amountMinor'=>12.34])),$o),'validation_error',422),'floating amounts rejected');
check(err(call('finance.push',push($scope,uuid(),'financeEntry',array_replace($p,['amountMinor'=>'1234'])),$o),'validation_error',422),'numeric string amounts rejected');
$tr=uuid();$transfer=['fromAccountId'=>$a,'toAccountId'=>$b,'amountMinor'=>3000,'currency'=>'EUR','status'=>'posted','title'=>'Contribution transfer','notes'=>'','occurredAt'=>$now,'createdAt'=>$now,'updatedAt'=>$now];$tp=push($scope,$tr,'financeTransfer',$transfer);data(call('finance.push',$tp,$m));
check(data(call('finance.push',$tp,$m))['replayed'],'lost transfer ACK retry returns original result');
$records=data(call('finance.pull',['scopeId'=>$scope,'cursor'=>0],$m))['records'];$income=0;$expense=0;$balances=[$a=>10000,$b=>0];foreach($records as$r){$x=$r['payload'];if($r['type']==='financeEntry'&&$x['status']==='posted'){$delta=$x['kind']==='income'?$x['amountMinor']:-$x['amountMinor'];$balances[$x['accountId']]+=$delta;if($delta>0){$income+=$delta;}else{$expense-=$delta;}}elseif($r['type']==='financeTransfer'&&$x['status']==='posted'){$balances[$x['fromAccountId']]-=$x['amountMinor'];$balances[$x['toAccountId']]+=$x['amountMinor'];}}
check($income===0&&$expense===1234&&$balances[$a]===7000&&$balances[$b]===1766,'transfer shifts balances without double-counting income or expense');
check(count(data(call('finance.audit',['scopeId'=>$scope,'recordId'=>$tr],$m))['entries'])===1,'transfer replay creates no second immutable audit revision');
check(err(call('finance.push',push($scope,uuid(),'financeTransfer',array_replace($transfer,['toAccountId'=>$a])),$m),'same_transfer_account',422),'same ledger account transfer rejected');
check(err(call('sync2.push',$ep,$o),'validation_error',422),'finance rejected from generic sync writes');
$generic=data(call('sync2.pull',['scopeId'=>$scope,'cursor'=>0],$m));check(count($generic['records'])===0&&$generic['cursor']===2,'finance does not leak records or finance sequence through generic pull');
check(err(call('finance.push',push($scope,$entry,'financeEntry',$p,1),$v),'finance_forbidden',403),'read grantee cannot write finance');
check(err(call('finance.pull',['scopeId'=>$scope,'cursor'=>0],$f),'permission_revoked',403),'foreign financial scope denied');
$stale=push($scope,$entry,'financeEntry',array_replace($p,['title'=>'Lost race']),1);$race=parallel([['finance.push',$stale,$o],['finance.push',push($scope,$entry,'financeEntry',array_replace($p,['title'=>'Other race']),1),$m]]);$statuses=array_column($race,'status');sort($statuses);check($statuses===[200,409],'simultaneous financial writes have one winner and one conflict');
$audit=data(call('finance.audit',['scopeId'=>$scope,'recordId'=>$entry],$m));check(count($audit['entries'])===2&&$audit['entries'][1]['before']===null&&$audit['entries'][0]['before']['payload']['title']==='Shared bill','immutable audit preserves original entry and author across update');
$inbox=data(call('inbox.sync',['cursor'=>0],$v));$financeItems=array_values(array_filter($inbox['items'],fn($x)=>$x['category']==='finance'));check(count($financeItems)>0&&strpos(json_encode($financeItems),'Shared bill')===false&&strpos(json_encode($financeItems),'amountMinor')===false,'finance inbox stores references without payload snapshots');
$oldPull=data(call('finance.pull',['scopeId'=>$scope,'cursor'=>0],$v));data(call('finance.grant',['scopeId'=>$scope,'accountId'=>$sessions['viewer']['user']['accountId'],'grant'=>'none','requestId'=>uuid()],$o));
$blocked=call('finance.push',push($scope,$entry,'financeEntry',$p,0),$v);check(err($blocked,'finance_forbidden',403)&&$blocked['body']['error']['details']===[],'revoked grant cannot use conflict to reveal canonical finance');
check(err(call('finance.audit',['scopeId'=>$scope,'recordId'=>$entry],$v),'finance_forbidden',403),'revocation hides immutable historic audit');
check(err(call('inbox.open',['id'=>$financeItems[0]['id']],$v),'permission_revoked',403),'historic finance inbox open denied after grant revocation');
check(err(call('inbox.sync',['cursor'=>$inbox['cursor'],'visibilityRevision'=>$inbox['visibilityRevision']],$v),'visibility_changed',409),'financial revocation invalidates inbox visibility epoch');
check(count(array_filter(data(call('inbox.sync',['cursor'=>0],$v))['items'],fn($x)=>$x['category']==='finance'))===0,'revoked grant hides historic finance inbox projection');
data(call('finance.grant',['scopeId'=>$scope,'accountId'=>$sessions['viewer']['user']['accountId'],'grant'=>'read','requestId'=>uuid()],$o));check(err(call('finance.pull',['scopeId'=>$scope,'cursor'=>$oldPull['cursor'],'accessRevision'=>$oldPull['accessRevision']],$v),'finance_access_changed',409),'regrant rejects pre-revocation finance cursor');$backfill=data(call('finance.pull',['scopeId'=>$scope,'cursor'=>0],$v));check(count($backfill['records'])===4,'regrant full backfill returns complete authorized state');
check(err(call('finance.push',push($scope,$a,'financeAccount',null,1,null,true),$o),'live_children',422),'financial account delete preserves live entry/transfer parents');
$grants=data(call('finance.grants',['scopeId'=>$scope],$o));check(count($grants['grants'])===3,'owner sees actual current finance grants without invented defaults');check(err(call('finance.grants',['scopeId'=>$scope],$v),'permission_revoked',403),'nonowner cannot enumerate grant administration');
// Controlled two-connection race: revocation commits while push waits for scope mutex.
if($sqlite){$pdo->exec('BEGIN IMMEDIATE');}else{$pdo->exec('SET TRANSACTION ISOLATION LEVEL READ COMMITTED');$pdo->beginTransaction();$q=$pdo->prepare('SELECT id FROM familyhub_scopes WHERE id=? FOR UPDATE');$q->execute([$scope]);$q->closeCursor();}
$pdo->prepare('UPDATE familyhub_finance_grants SET access_level=\'none\' WHERE scope_id=? AND account_id=?')->execute([$scope,$sessions['member']['user']['accountId']]);$pdo->prepare('UPDATE familyhub_finance_policy SET revision=revision+1 WHERE scope_id=?')->execute([$scope]);
$h=handle('finance.push',push($scope,$entry,'financeEntry',$p,2),$m);$multi=curl_multi_init();curl_multi_add_handle($multi,$h);$until=microtime(true)+0.2;do{curl_multi_exec($multi,$running);if($running){curl_multi_select($multi,0.02);}}while($running&&microtime(true)<$until);check($running===1,'financial push waits behind scope-serialized grant change');
if($sqlite){$pdo->exec('COMMIT');}else{$pdo->commit();}do{curl_multi_exec($multi,$running);if($running){curl_multi_select($multi,0.1);}}while($running);$result=['status'=>curl_getinfo($h,CURLINFO_HTTP_CODE),'body'=>json_decode(curl_multi_getcontent($h),true)];curl_multi_remove_handle($multi,$h);curl_close($h);curl_multi_close($multi);check(err($result,'finance_forbidden',403)&&$result['body']['error']['details']===[],'blocked push reads committed revocation rather than stale grant snapshot');
data(call('scopes.removeMember',['scopeId'=>$scope,'userId'=>$users['member'],'requestId'=>uuid()],$o));$current=$audit['entries'][0]['after'];$p2=array_replace($current['payload'],['notes'=>'Corrected with former payer']);check(data(call('finance.push',push($scope,$entry,'financeEntry',$p2,2),$o))['record']['revision']===3,'unchanged former payer UUID permits correction without history loss');check(err(call('finance.push',push($scope,uuid(),'financeEntry',$p),$o),'assignee_not_member',422),'new financial attribution to inactive member rejected');
check(data(call('finance.push',push($scope,$a,'financeAccount',array_replace($account,['name'=>'Corrected former holder']),1),$o))['record']['revision']===2,'unchanged former holder permits account correction');
check(data(call('finance.policy',['scopeId'=>$scope],$o))['grant']==='write','member removal preserves other finance grants');
echo 'SUCCESS '.$checks.' finance checks ('.$pdo->getAttribute(PDO::ATTR_DRIVER_NAME).')'.PHP_EOL;
