<?php
// Fresh actual-HTTP fixtures and schema12 regressions; never production data.
require __DIR__.'/spaces-integration.php';
$checks = 0;
foreach (['linked-payment-ip:','finance-ip:','sync-ip:','invitation-ip:','scopes-ip:'] as $key) {
    $pdo->prepare('DELETE FROM familyhub_rate_limits WHERE id=?')->execute([hash('sha256',$key.'127.0.0.1')]);
}
$sourceOrg = uuid();
data(call('scopes.create',['id'=>$sourceOrg,'kind'=>'organization','name'=>'Linked payment organization','accessPolicyVersion'=>2,'requestId'=>uuid()],$o));
$source = uuid();
data(call('scopes.create',['id'=>$source,'kind'=>'project','name'=>'Linked project','organizationId'=>$sourceOrg,'requestId'=>uuid()],$o));
invite($source,$names['external'],$o,$e);
$orgAccount = uuid();
$projectAccount = uuid();
$richAccount = $accountPayload + ['openingBalanceAt'=>null,'archived'=>false];
data(call('finance2.push',['scopeId'=>$sourceOrg,'operation'=>operation($orgAccount,'financeAccount',$richAccount)],$o));
data(call('finance2.push',['scopeId'=>$source,'operation'=>operation($projectAccount,'financeAccount',$richAccount)],$o));
$private = data(call('personal.ensure',[],$o))['scope']['id'];
$card = uuid();
$privateAccount = ['name'=>'Private card never shared','currency'=>'EUR','openingBalanceMinor'=>0,'openingBalanceAt'=>null,'archived'=>false,'createdAt'=>$stamp,'updatedAt'=>$stamp];
data(call('finance2.push',['scopeId'=>$private,'operation'=>operation($card,'personalFinanceAccount',$privateAccount)],$o));
$expense = uuid();
$payload = array_replace($costPayload,['accountId'=>$projectAccount,'ledgerAccountId'=>$projectAccount,'taskId'=>null,'status'=>'posted','title'=>'Canonical 30 EUR','paidAt'=>$stamp]);
$ordinary = ['scopeId'=>$source,'operation'=>operation($expense,'financeEntry',$payload)];
data(call('finance2.push',$ordinary,$o));
$eventId = uuid();
$commit = ['scopeId'=>$source,'entryId'=>$expense,'expectedEntryRevision'=>1,'eventId'=>$eventId,'paidAt'=>$stamp,'expectReimbursement'=>true,'requestId'=>uuid(),'personalTarget'=>['scopeId'=>$private,'accountId'=>$card],'householdScopeId'=>$house];
denied(call('finance3.paymentCommit',$commit,$e),'finance_forbidden','accepted reader cannot approve personal payment');
$event = data(call('finance3.paymentCommit',$commit,$o))['event'];
check($event['amountMinor']===3000 && $event['sourceRevision']===2 && $event['payerAccountId']===$sessions['owner']['user']['accountId'],'canonical expense becomes one full identity-bound payment');
check(data(call('finance3.paymentCommit',$commit,$o))['event']===$event,'lost commit ACK replays exact event once');
denied(call('finance2.policy',['scopeId'=>$source],$o),'client_upgrade_required','old client cannot obtain misleading complete linked financial policy');
denied(call('finance2.pull',['scopeId'=>$source,'cursor'=>0],$e),'client_upgrade_required','old reader must upgrade before linked financial pull');
$aware = ['scopeId'=>$source,'linkedPaymentsAware'=>true];
check(data(call('finance2.policy',$aware,$o))['linkedPaymentsRequired'],'new aware client learns complete sidecar is required');
check(data(call('finance2.push',$ordinary+['linkedPaymentsAware'=>true],$o))['replayed'],'ordinary original finance2 hash survives aware transport upgrade');
$initial = data(call('finance3.payments',['scopeId'=>$private],$o));
check($initial['cashMovements'][0]['amountMinor']===-3000 && $initial['projections'][0]['privateAccountId']===$card,'private debit uses selected personal card');
$houseRead = data(call('finance3.payments',['scopeId'=>$house],$o));
check(!str_contains(json_encode($houseRead),$card) && !str_contains(json_encode($houseRead),'Private card'),'household projection excludes private account identity and card name');
check(!str_contains(json_encode(data(call('finance3.payments',['scopeId'=>$source],$e))),$card),'project finance reader never sees private card identity');
$edit = ['scopeId'=>$source,'operation'=>operation($expense,'financeEntry',array_replace($payload,['amountMinor'=>4000]),2),'linkedPaymentsAware'=>true];
denied(call('finance2.push',$edit,$o),'linked_payment_source_locked','linked canonical expense cannot be silently rewritten');
denied(call('finance2.push',['scopeId'=>$source,'operation'=>operation($expense,'financeEntry',null,2,null,true),'linkedPaymentsAware'=>true],$o),'linked_payment_source_locked','linked canonical expense cannot be silently deleted');
$refund10 = ['scopeId'=>$source,'eventId'=>$eventId,'expectedRevision'=>1,'legId'=>uuid(),'amountMinor'=>1000,'paidAt'=>'2026-10-10T08:00:00Z','organizationAccountScopeId'=>$sourceOrg,'organizationAccountId'=>$orgAccount,'requestId'=>uuid()];
denied(call('finance3.paymentReimburse',$refund10,$e),'finance_forbidden','household/project reader cannot fabricate approved refund');
$partial = data(call('finance3.paymentReimburse',$refund10,$o))['event'];
check($partial['revision']===2 && array_sum(array_column($partial['reimbursements'],'amountMinor'))===1000,'first partial approved refund settles 10 of 30 EUR');
check(data(call('finance3.paymentReimburse',$refund10,$o))['event']===$partial,'lost partial refund ACK replays immutable leg');
$refundKey=hash('sha256',$source.':paymentRefund:'.$eventId.':'.$refund10['legId']);
$notifications=$pdo->prepare('SELECT id FROM familyhub_inbox WHERE event_key=? AND recipient_account_id=?');
$notifications->execute([$refundKey,$sessions['external']['user']['accountId']]);
$refundNotifications=$notifications->fetchAll(PDO::FETCH_ASSOC);$notifications->closeCursor();
check(count($refundNotifications)===1,'refund replay creates one financial notification per permitted recipient');
$refundOpen=data(call('inbox.open',['id'=>(int)$refundNotifications[0]['id'],'financeContractVersion'=>2],$e));
check($refundOpen['record']['id']===$expense&&$refundOpen['target']['scopeId']===$source,'refund notification opens canonical expense in source scope');
$private10 = data(call('finance3.payments',['scopeId'=>$private],$o));
check(array_sum(array_column($private10['cashMovements'],'amountMinor'))===-2000,'private cash burden is 20 EUR after first refund');
$org10 = data(call('finance3.payments',['scopeId'=>$sourceOrg],$o));
check(array_sum(array_column($org10['cashMovements'],'amountMinor'))===-1000 && $org10['events']===[],'refund debits selected parent organization ledger without duplicate expense');
check(data(call('finance3.payments',['scopeId'=>$source],$o))['scopeSequence']>2,'refund advances ordinary sync signal for second device');
$refund20 = array_replace($refund10,['expectedRevision'=>2,'legId'=>uuid(),'amountMinor'=>2000,'paidAt'=>'2026-10-11T08:00:00Z','requestId'=>uuid()]);
$settled = data(call('finance3.paymentReimburse',$refund20,$o))['event'];
check(array_sum(array_column($settled['reimbursements'],'amountMinor'))===3000,'second partial approved refund settles remaining 20 EUR');
check(array_sum(array_column(data(call('finance3.payments',['scopeId'=>$private],$o))['cashMovements'],'amountMinor'))===0,'fully refunded private cash burden returns to zero');
denied(call('finance3.paymentReimburse',array_replace($refund20,['expectedRevision'=>3,'legId'=>uuid(),'amountMinor'=>1,'requestId'=>uuid()]),$o),'reimbursement_exceeds_payment','over refund rejected without income or duplicate expense');
denied(call('finance3.paymentReimburse',array_replace($refund20,['requestId'=>uuid()]),$o),'payment_changed','stale financial event revision is rejected');
denied(call('finance3.paymentProject',['scopeId'=>$source,'eventId'=>$eventId,'expectedRevision'=>3,'requestId'=>uuid(),'householdScopeId'=>$house],$e),'finance_forbidden','foreign payer cannot copy another private payment to household');
$foreignPrivate = data(call('personal.ensure',[],$e))['scope']['id'];
denied(call('finance3.paymentProject',['scopeId'=>$source,'eventId'=>$eventId,'expectedRevision'=>3,'requestId'=>uuid(),'personalTarget'=>['scopeId'=>$foreignPrivate,'accountId'=>$card]],$o),'permission_revoked','source writer cannot attach payment to foreign personal space');
// General organization expense and explicit no-reimbursement route.
$ownExpense = uuid();
$orgPayload = array_replace($payload,['accountId'=>$orgAccount,'ledgerAccountId'=>$orgAccount]);
data(call('finance2.push',['scopeId'=>$sourceOrg,'operation'=>operation($ownExpense,'financeEntry',$orgPayload),'linkedPaymentsAware'=>true],$o));
$noRefund = data(call('finance3.paymentCommit',['scopeId'=>$sourceOrg,'entryId'=>$ownExpense,'expectedEntryRevision'=>1,'eventId'=>uuid(),'paidAt'=>$stamp,'expectReimbursement'=>false,'requestId'=>uuid()],$o))['event'];
check(!$noRefund['expectReimbursement'],'general organization source supports explicit payment without receivable');
denied(call('finance3.paymentReimburse',['scopeId'=>$sourceOrg,'eventId'=>$noRefund['eventId'],'expectedRevision'=>1,'legId'=>uuid(),'amountMinor'=>100,'paidAt'=>$stamp,'organizationAccountId'=>$orgAccount,'requestId'=>uuid()],$o),'reimbursement_not_expected','no-reimbursement payment cannot fabricate settlement');
data(call('scopes.removeMember',['scopeId'=>$source,'userId'=>$ids['external'],'requestId'=>uuid()],$o));
denied(call('finance3.payments',['scopeId'=>$source],$e),'permission_revoked','revoke stops further linked payment reads');
denied(call('inbox.open',['id'=>(int)$refundNotifications[0]['id'],'financeContractVersion'=>2],$e),'permission_revoked','revoked recipient cannot open retained refund notification');
// Explicit oversized snapshot failure, with no partial success.
$huge = str_repeat('x',524289);
$pdo->prepare('UPDATE familyhub_payment_events SET data=? WHERE scope_id=? AND event_id=?')->execute([$huge,$source,$eventId]);
denied(call('finance3.payments',['scopeId'=>$source],$o),'linked_payments_too_large','oversized full snapshot is clearly incomplete');
$pdo->prepare('UPDATE familyhub_payment_events SET data=? WHERE scope_id=? AND event_id=?')->execute([json_encode($settled),$source,$eventId]);
// Harmless linked task timeline edit must not alter payment/refund dates.
$linkedTask=uuid();
data(call('sync3.push',['scopeId'=>$source,'operation'=>operation($linkedTask,'task',array_replace($taskPayload,['projectId'=>$source,'dueAt'=>$stamp])),'operationContractVersion'=>3],$o));
$taskExpense=uuid();
$taskCost=array_replace($payload,['taskId'=>$linkedTask,'plannedAt'=>$stamp,'paidAt'=>null]);
data(call('finance2.push',['scopeId'=>$source,'operation'=>operation($taskExpense,'financeEntry',$taskCost),'linkedPaymentsAware'=>true],$o));
$taskPaid=data(call('finance3.paymentCommit',['scopeId'=>$source,'entryId'=>$taskExpense,'expectedEntryRevision'=>1,'eventId'=>uuid(),'paidAt'=>$stamp,'expectReimbursement'=>true,'requestId'=>uuid()],$o))['event'];
data(call('sync3.push',['scopeId'=>$source,'operation'=>operation($linkedTask,'task',array_replace($taskPayload,['projectId'=>$source,'dueAt'=>'2026-10-20T08:00:00Z']),1),'operationContractVersion'=>3],$o));
$taskCurrent=array_values(array_filter(data(call('finance2.pull',['scopeId'=>$source,'cursor'=>0,'linkedPaymentsAware'=>true],$o))['records'],fn($r)=>$r['id']===$taskExpense))[0];
check(new DateTimeImmutable($taskCurrent['payload']['paidAt'])==new DateTimeImmutable($stamp),'linked task due change preserves approved payment date');
check($taskCurrent['revision']===2,'linked task-only timeline edit does not rewrite financial history');
$safeTaskCost=array_replace($taskCurrent['payload'],['title'=>'Safely renamed paid task expense','notes'=>'Shared clarification','plannedAt'=>'2026-10-20T08:00:00Z']);
data(call('finance2.push',['scopeId'=>$source,'operation'=>operation($taskExpense,'financeEntry',$safeTaskCost,2),'linkedPaymentsAware'=>true],$o));
$safeTaskEvent=array_values(array_filter(data(call('finance3.payments',['scopeId'=>$source],$o))['events'],fn($r)=>$r['eventId']===$taskPaid['eventId']))[0];
check($safeTaskEvent['sourceRevision']===3&&$safeTaskEvent['revision']===2&&new DateTimeImmutable($safeTaskEvent['paidAt'])==new DateTimeImmutable($stamp),'safe paid expense metadata edit updates source proof without changing monetary dates');
// Retained/transferred shared facts survive payer account deletion, private links do not.
$payerName=$prefix.'_payment_delete';$payerId=$container['userModel']->create(['username'=>$payerName,'password'=>$password,'role'=>'app-user']);
$payerSession=data(call('auth.login',['username'=>$payerName,'password'=>$password,'deviceName'=>'Disposable linked payer']));$pt=$payerSession['token'];
$retainedOrg=uuid();data(call('scopes.create',['id'=>$retainedOrg,'kind'=>'organization','name'=>'Retained linked source','accessPolicyVersion'=>2,'requestId'=>uuid()],$pt));
invite($retainedOrg,$names['external'],$pt,$e);
$retainedAccount=uuid();data(call('finance2.push',['scopeId'=>$retainedOrg,'operation'=>operation($retainedAccount,'financeAccount',$richAccount)],$pt));
$retainedExpense=uuid();data(call('finance2.push',['scopeId'=>$retainedOrg,'operation'=>operation($retainedExpense,'financeEntry',array_replace($payload,['accountId'=>$retainedAccount,'ledgerAccountId'=>$retainedAccount,'notes'=>'Author-specific note']))],$pt));
$receiptHouse=uuid();data(call('scopes.create',['id'=>$receiptHouse,'kind'=>'household','name'=>'Receipt household','requestId'=>uuid()],$e));data(call('finance.enable',['scopeId'=>$receiptHouse,'enabled'=>true,'requestId'=>uuid()],$e));
invite($receiptHouse,$payerName,$e,$pt);data(call('finance.grant',['scopeId'=>$receiptHouse,'accountId'=>$payerSession['user']['accountId'],'grant'=>'write','requestId'=>uuid()],$e));
$payerPrivate=data(call('personal.ensure',[],$pt))['scope']['id'];$payerCard=uuid();data(call('finance2.push',['scopeId'=>$payerPrivate,'operation'=>operation($payerCard,'personalFinanceAccount',$privateAccount)],$pt));
$retainedEvent=data(call('finance3.paymentCommit',['scopeId'=>$retainedOrg,'entryId'=>$retainedExpense,'expectedEntryRevision'=>1,'eventId'=>uuid(),'paidAt'=>$stamp,'expectReimbursement'=>true,'personalTarget'=>['scopeId'=>$payerPrivate,'accountId'=>$payerCard],'householdScopeId'=>$receiptHouse,'requestId'=>uuid()],$pt))['event'];
denied(call('account.deletion.preview',['policyVersion'=>2],$pt),'client_upgrade_required','legacy deletion client must review new retained linked financial facts');
$review=data(call('account.deletion.preview',['policyVersion'=>3],$pt));
check($review['policyVersion']===3&&$review['impact']['privatePaymentProjectionsDeleted']===1&&$review['linkedFinancialFacts'][0]['eventsRetainedIfScopeKept']===1,'fresh deletion review counts private removal and conditional retained shared financial fact');
$choices=array_map(fn($r)=>['scopeId'=>$r['scopeId'],'recordId'=>$r['recordId'],'action'=>$r['action']],$review['resolutions']);
data(call('account.deletion.confirm',['operationId'=>uuid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$review['previewHash'],'password'=>$password,'confirmation'=>'DELETE','policyVersion'=>3,'ownershipTransfers'=>[['scopeId'=>$retainedOrg,'successorAccountId'=>$sessions['external']['user']['accountId']]],'resolutions'=>$choices],$pt));
$retained=data(call('finance2.pull',['scopeId'=>$retainedOrg,'cursor'=>0,'linkedPaymentsAware'=>true],$e))['records'];
$retainedRow=array_values(array_filter($retained,fn($r)=>$r['id']===$retainedExpense))[0];
check(!$retainedRow['deleted']&&$retainedRow['payload']['amountMinor']===3000&&$retainedRow['payload']['notes']===''&&$retainedRow['payload']['payerAccountId']===null,'transferred linked expense retains amount/date with removed member presentation');
$retainedReceipt=data(call('finance3.payments',['scopeId'=>$receiptHouse],$e))['projections'][0];
check(!isset($retainedReceipt['privateAccountId'])&&$retainedReceipt['state']==='complete','already shared household cash receipt survives without private card link');
$statement=$pdo->prepare('SELECT COUNT(*) FROM familyhub_payment_projections WHERE scope_id=?');$statement->execute([$payerPrivate]);check((int)$statement->fetchColumn()===0,'deleted account leaves no private linked projection');$statement->closeCursor();
// An explicitly deleted source must mark downstream historical receipt as source removed.
$removeName=$prefix.'_source_delete';$removeId=$container['userModel']->create(['username'=>$removeName,'password'=>$password,'role'=>'app-user']);$removeSession=data(call('auth.login',['username'=>$removeName,'password'=>$password,'deviceName'=>'Disposable source']));$rt=$removeSession['token'];
$removedOrg=uuid();data(call('scopes.create',['id'=>$removedOrg,'kind'=>'organization','name'=>'Explicitly removed source','accessPolicyVersion'=>2,'requestId'=>uuid()],$rt));
$removedAccount=uuid();data(call('finance2.push',['scopeId'=>$removedOrg,'operation'=>operation($removedAccount,'financeAccount',$richAccount)],$rt));
$removedExpense=uuid();data(call('finance2.push',['scopeId'=>$removedOrg,'operation'=>operation($removedExpense,'financeEntry',array_replace($payload,['accountId'=>$removedAccount,'ledgerAccountId'=>$removedAccount]))],$rt));
invite($receiptHouse,$removeName,$e,$rt);data(call('finance.grant',['scopeId'=>$receiptHouse,'accountId'=>$removeSession['user']['accountId'],'grant'=>'write','requestId'=>uuid()],$e));
$removedEvent=data(call('finance3.paymentCommit',['scopeId'=>$removedOrg,'entryId'=>$removedExpense,'expectedEntryRevision'=>1,'eventId'=>uuid(),'paidAt'=>$stamp,'expectReimbursement'=>false,'householdScopeId'=>$receiptHouse,'requestId'=>uuid()],$rt))['event'];
$removeReview=data(call('account.deletion.preview',['policyVersion'=>3],$rt));
data(call('account.deletion.confirm',['operationId'=>uuid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$removeReview['previewHash'],'password'=>$password,'confirmation'=>'DELETE','policyVersion'=>3,'ownedScopeDeletions'=>[$removedOrg]],$rt));
$removedReceipt=array_values(array_filter(data(call('finance3.payments',['scopeId'=>$receiptHouse],$e))['projections'],fn($r)=>$r['eventId']===$removedEvent['eventId']))[0];
check($removedReceipt['state']==='sourceRemoved','deleted canonical source never leaves downstream receipt marked current');
$statement=$pdo->prepare('SELECT COUNT(*) FROM familyhub_payment_events WHERE scope_id=?');$statement->execute([$removedOrg]);check((int)$statement->fetchColumn()===0,'explicit source deletion removes canonical payment sidecars');$statement->closeCursor();
require __DIR__.'/linked-payments-web.php';
echo 'PASS: '.$checks.' linked payment HTTP checks ('.$pdo->getAttribute(PDO::ATTR_DRIVER_NAME).')'.PHP_EOL;
