<?php
require '/var/www/app/app/common.php';
if (session_status() === PHP_SESSION_ACTIVE) { session_abort(); }
if (!defined('FAMILYHUB_DEVELOPMENT_MODE') || FAMILYHUB_DEVELOPMENT_MODE !== true) { throw new RuntimeException('Synthetic development only'); }
use Kanboard\Plugin\FamilyHub\Model\NativeService;
use Kanboard\Plugin\FamilyHub\Model\NativeError;
$checks=0; $pdo=$container['db']->getConnection(); $service=new NativeService($container); $prefix='private_'.bin2hex(random_bytes(5)); $ip='synthetic-private-'.bin2hex(random_bytes(6));
function uuid() { $h=bin2hex(random_bytes(16)); return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20); }
function check($v,$m) { global $checks; if(!$v){throw new RuntimeException('FAIL: '.$m);} $checks++; echo 'PASS: '.$m.PHP_EOL; }
function callApi($op,$p,$token='') { global $service,$ip; return $service->dispatch($op,$p,$token?'Bearer '.$token:'',$ip); }
function deny($op,$p,$token,$code,$m) { try{callApi($op,$p,$token);$denied=false;}catch(NativeError $e){$denied=$e->errorCode===$code;} check($denied,$m); }
function putRecord($scope,$id,$type,$payload,$token,$rev=0,$delete=false) { return callApi('sync2.push',['scopeId'=>$scope,'operation'=>['opId'=>uuid(),'recordId'=>$id,'type'=>$type,'expectedRevision'=>$rev,'deleted'=>$delete,'payload'=>$payload]],$token); }
function putFinance($scope,$id,$payload,$token,$rev=0,$delete=false,$type='personalFinanceEntry') { return callApi('finance.push',['scopeId'=>$scope,'operation'=>['opId'=>uuid(),'recordId'=>$id,'type'=>$type,'expectedRevision'=>$rev,'deleted'=>$delete,'payload'=>$payload]],$token); }
$pw=bin2hex(random_bytes(16));
foreach(['a','b'] as $suffix){$uid=$container['userModel']->create(['username'=>$prefix.'_'.$suffix,'password'=>$pw,'role'=>'app-user']);$sessions[$suffix]=callApi('auth.login',['username'=>$prefix.'_'.$suffix,'password'=>$pw,'deviceName'=>'Private test']);}
$a=$sessions['a'];$b=$sessions['b'];$token=$a['token'];$foreign=$b['token'];$account=$a['user']['accountId'];
$cap=callApi('capabilities',[]);check($cap['features']['privateSync']&&$cap['features']['personalFinanceEntry']&&in_array('personal',$cap['scopeKinds'],true),'private capability and personal scope advertised');
deny('personal.ensure',[],'','auth_required','personal creation requires bearer');
$scope=callApi('personal.ensure',[],$token)['scope'];$id=$scope['id'];check($scope['kind']==='personal'&&$scope['role']==='owner','personal scope owner wire shape');check(callApi('personal.ensure',[],$token)['scope']['id']===$id,'ensure replay returns persistent same scope');
$second=callApi('auth.login',['username'=>$prefix.'_a','password'=>$pw,'deviceName'=>'Second private device']);check(callApi('personal.ensure',[],$second['token'])['scope']['id']===$id,'same account second device shares singleton');check(callApi('personal.ensure',[],$foreign)['scope']['id']!==$id,'different account separate private UUID');
check(count(array_filter(callApi('scopes.list',[],$token)['scopes'],fn($r)=>$r['kind']==='personal'))===0,'legacy scopes list excludes new private kind');
check(count(array_filter(callApi('scopes.list',['includePersonal'=>true],$token)['scopes'],fn($r)=>$r['id']===$id))===1,'new scopes list explicit personal opt-in');
deny('personal.ensure',['accountId'=>$b['user']['accountId']],$token,'validation_error','personal account spoof rejected');
deny('scopes.members',['scopeId'=>$id],$foreign,'permission_revoked','foreign personal membership directory denied');
deny('invitations.create',['scopeId'=>$id,'recipientUsername'=>$prefix.'_b','role'=>'member','requestId'=>uuid()],$token,'personal_not_shareable','owner cannot invite into personal scope');
deny('finance.grant',['scopeId'=>$id,'accountId'=>$b['user']['accountId'],'grant'=>'write','requestId'=>uuid()],$token,'personal_not_shareable','owner cannot extend private financial grant');
deny('finance.enable',['scopeId'=>$id,'enabled'=>false,'requestId'=>uuid()],$token,'personal_not_shareable','private financial policy cannot be changed through shared settings');
deny('sync2.pull',['scopeId'=>$id,'cursor'=>0],$foreign,'permission_revoked','foreign generic private pull denied');
deny('finance.pull',['scopeId'=>$id,'cursor'=>0],$foreign,'permission_revoked','foreign private finance pull denied');
$pdo->prepare('INSERT INTO familyhub_members VALUES(?,?,?,\'owner\',1)')->execute([$id,$b['user']['id'],$b['user']['accountId']]);
deny('sync2.pull',['scopeId'=>$id,'cursor'=>0],$foreign,'permission_revoked','injected member/role cannot expose private scope');check(count(array_filter(callApi('scopes.list',[],$foreign)['scopes'],fn($r)=>$r['id']===$id))===0,'injected member does not list private scope');check(count(callApi('scopes.members',['scopeId'=>$id],$token)['members'])===1,'personal directory remains owner only despite injected member');check(!(new \Kanboard\Plugin\FamilyHub\Model\NativeFinanceAccess($container))->visible($id,$b['user']['accountId'],true),'private inbox visibility ignores injected memberships');
$now='2026-10-05T10:00:00.000Z';$project=uuid();$payload=['title'=>str_repeat('Ž',500),'description'=>str_repeat('漢',50000),'area'=>'personal','createdAt'=>$now,'updatedAt'=>$now,'startAt'=>null,'endAt'=>null];$record=putRecord($id,$project,'project',$payload,$token)['record'];check($record['payload']===$payload,'private longest local Unicode values preserved exactly');
$rows=callApi('sync2.pull',['scopeId'=>$id,'cursor'=>0],$second['token'])['records'];check(count($rows)===1&&$rows[0]['payload']===$payload,'second device reads exact large personal record');check(count(callApi('inbox.sync',['cursor'=>0],$foreign)['items'])===0,'injected foreign member receives no personal notifications');
$task=uuid();$taskPayload=['title'=>'Private task','notes'=>str_repeat("\n",50000),'projectId'=>$project,'dueAt'=>null,'isCompleted'=>false,'startAt'=>null,'endAt'=>null,'assigneeAccountIds'=>[],'createdAt'=>$now,'updatedAt'=>$now];check(putRecord($id,$task,'task',$taskPayload,$token)['record']['payload']===$taskPayload,'escaped control characters preserve full local notes');
$tooLong=$payload;$tooLong['title']=str_repeat('😀',251);deny('sync2.push',['scopeId'=>$id,'operation'=>['opId'=>uuid(),'recordId'=>uuid(),'type'=>'project','expectedRevision'=>0,'deleted'=>false,'payload'=>$tooLong]],$token,'validation_error','private bounds match UTF16 units for astral characters');
$shared=callApi('scopes.create',['id'=>uuid(),'kind'=>'household','name'=>'Synthetic','requestId'=>uuid()],$token)['scope']['id'];deny('sync2.push',['scopeId'=>$shared,'operation'=>['opId'=>uuid(),'recordId'=>uuid(),'type'=>'project','expectedRevision'=>0,'deleted'=>false,'payload'=>$payload]],$token,'validation_error','shared byte limits remain unchanged');
$fId=uuid();$finance=['title'=>str_repeat('F',500),'amountMinor'=>123456789,'currency'=>'EUR','kind'=>'expense','occurredAt'=>$now,'projectId'=>$project,'notes'=>str_repeat('漢',50000),'createdAt'=>$now,'updatedAt'=>$now];$f=putFinance($id,$fId,$finance,$token);check($f['record']['payload']===$finance&&$f['record']['createdByAccountId']===$account,'private finance preserves fields and author without artificial account');check(callApi('finance.pull',['scopeId'=>$id,'cursor'=>0],$second['token'])['records'][0]['payload']===$finance,'private finance separate cursor reads full personal payload');check(count(callApi('sync2.pull',['scopeId'=>$id,'cursor'=>0],$token)['records'])===2,'generic private sync excludes financial record');
deny('sync2.push',['scopeId'=>$id,'operation'=>['opId'=>uuid(),'recordId'=>uuid(),'type'=>'personalFinanceEntry','expectedRevision'=>0,'deleted'=>false,'payload'=>$finance]],$token,'validation_error','generic sync rejects financial type');
callApi('finance.enable',['scopeId'=>$shared,'enabled'=>true,'requestId'=>uuid()],$token);deny('finance.push',['scopeId'=>$shared,'operation'=>['opId'=>uuid(),'recordId'=>uuid(),'type'=>'personalFinanceEntry','expectedRevision'=>0,'deleted'=>false,'payload'=>$finance]],$token,'validation_error','private finance type cannot be copied into shared space');
$taskPayload['projectId']=null;putRecord($id,$task,'task',$taskPayload,$token,1);
try{putRecord($id,$project,'project',null,$token,1,true);$denied=false;}catch(NativeError $e){$denied=$e->errorCode==='live_children'&&$e->details['serverRecord']['id']===$project;}check($denied,'project delete waits for private financial unlink ACK');
$finance['projectId']=null;putFinance($id,$fId,$finance,$token,1);check(putRecord($id,$project,'project',null,$token,1,true)['record']['deleted'],'project delete succeeds after private financial unlink');check(callApi('finance.audit',['scopeId'=>$id,'recordId'=>$fId],$token)['entries'][0]['before']['payload']['projectId']===$project,'private finance audit preserves old project attribution');
$financialOp=['scopeId'=>$id,'operation'=>['opId'=>uuid(),'recordId'=>$fId,'type'=>'personalFinanceEntry','expectedRevision'=>2,'deleted'=>false,'payload'=>array_merge($finance,['title'=>'Changed'])]];$ack=callApi('finance.push',$financialOp,$token);check(callApi('finance.push',$financialOp,$token)['replayed']&&$ack['record']['revision']===3,'private finance lost ACK retry exactly once');
$bad=$financialOp;$bad['operation']['opId']=uuid();deny('finance.push',$bad,$second['token'],'conflict','second private device conflict is explicit');
deny('finance.audit',['scopeId'=>$id,'recordId'=>$fId],$foreign,'permission_revoked','foreign private historical audit denied');
echo 'SUCCESS '.$checks.' personal checks ('.$pdo->getAttribute(PDO::ATTR_DRIVER_NAME).')'.PHP_EOL;
