<?php
// Real SMTP protocol against a guarded local synthetic receiver. No external delivery.
$port=random_int(30000,40000);
define('FAMILYHUB_SMTP_HOST','127.0.0.1');define('FAMILYHUB_SMTP_PORT',$port);define('FAMILYHUB_SMTP_ENCRYPTION','none');define('FAMILYHUB_SMTP_ALLOW_LOCAL_PLAINTEXT',true);define('FAMILYHUB_SMTP_FROM','sender@capture.invalid');define('MAIL_BCC',['forbidden@capture.invalid']);
require '/var/www/app/app/common.php';
if(!defined('FAMILYHUB_DEVELOPMENT_MODE')||FAMILYHUB_DEVELOPMENT_MODE!==true){throw new RuntimeException('Development only');}
use Kanboard\Plugin\FamilyHub\Model\NativeSmtpTransport;
use Kanboard\Plugin\FamilyHub\Model\NativeNotificationWriter;
use Kanboard\Plugin\FamilyHub\Model\NativeDeliveryService;
$checks=0;$pdo=$container['db']->getConnection();$prefix='smtp_'.bin2hex(random_bytes(4));$scope=uuid();$target=uuid();$output='/tmp/familyhub-smtp-'.bin2hex(random_bytes(8)).'.json';
function uuid(){$h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20);}
function check($ok,$message){global$checks;if(!$ok){throw new RuntimeException('FAIL: '.$message);}$checks++;echo 'PASS: '.$message.PHP_EOL;}
function capture(){global$output;return json_decode(file_get_contents($output),true);}
$process=proc_open([PHP_BINARY,'/familyhub-tests/smtp-capture.php',$output,(string)$port],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);
if(!is_resource($process)){throw new RuntimeException('Capture unavailable');}stream_set_timeout($pipes[1],5);if(trim(fgets($pipes[1]))!=='ready'){throw new RuntimeException('Capture not ready');}
try{
 $uid=$container['userModel']->create(['username'=>$prefix,'password'=>bin2hex(random_bytes(16)),'email'=>'recipient@capture.invalid','role'=>'app-user']);$session=(new \Kanboard\Plugin\FamilyHub\Model\NativeAuthService($container))->issue($container['userModel']->getById($uid),'Synthetic SMTP');$account=$session['user']['accountId'];$token=$session['token'];unset($session);
 $pdo->prepare('INSERT INTO familyhub_scopes(id,kind,name,owner_id,sequence,created_at) VALUES(?,\'household\',\'Synthetic SMTP\',?,0,?)')->execute([$scope,$uid,time()]);$pdo->prepare('INSERT INTO familyhub_members(scope_id,user_id,account_id,role,active) VALUES(?,?,?,\'owner\',1)')->execute([$scope,$uid,$account]);
 $pdo->prepare('INSERT INTO familyhub_inbox_preferences VALUES(?,?,?,?)')->execute([$scope,$account,'tasks',json_encode(['inApp'=>true,'sound'=>false,'push'=>false,'email'=>true])]);
 $writer=new NativeNotificationWriter($container);$pdo->beginTransaction();$writer->insert($scope,$account,null,'task',$target,1,'task.created','tasks','scope',hash('sha256',$prefix.':1'));$pdo->commit();

 $result=(new NativeDeliveryService($container))->run(1);check($result['accepted']===1,'bounded delivery records explicit SMTP acceptance');$messages=capture()['messages'];check(count($messages)===1&&$messages[0]['recipients']===['recipient@capture.invalid'],'SMTP sends exactly one designated recipient and ignores global BCC');
 $body=$messages[0]['body'];check(strpos($body,'forbidden@')===false&&strpos($body,'amountMinor')===false&&strpos($body,$target)===false&&strpos($body,'task.created')===false,'SMTP body contains no source title, category, target or financial payload');check(preg_match('/Message-ID: <familyhub\.[0-9]+\.[a-f0-9]+@capture.invalid>/i',$body)===1,'stable reference-derived SMTP Message-ID');
 check((new NativeDeliveryService($container))->run(1)['accepted']===0&&count(capture()['messages'])===1,'accepted queue job not resent on cron repeat');
 try{(new NativeSmtpTransport())->send('outside@example.com',1,$account);$blocked=false;}catch(\Throwable$e){$blocked=true;}check($blocked,'development plaintext SMTP cannot address real external recipient');
 file_put_contents($output.'.mode','reject');$pdo->beginTransaction();$writer->insert($scope,$account,null,'task',$target,2,'task.updated','tasks','scope',hash('sha256',$prefix.':2'));$pdo->commit();$result=(new NativeDeliveryService($container))->run(1);check($result['retry']===1&&$result['accepted']===0,'SMTP recipient rejection remains pending with durable retry');
 $q=$pdo->prepare('SELECT state,attempts,next_attempt FROM familyhub_deliveries WHERE state=\'pending\' AND inbox_id IN (SELECT id FROM familyhub_inbox WHERE scope_id=?) ORDER BY inbox_id DESC LIMIT 1');$q->execute([$scope]);$job=$q->fetch(PDO::FETCH_ASSOC);$q->closeCursor();check($job['state']==='pending'&&(int)$job['attempts']===1&&(int)$job['next_attempt']>time(),'durable failed delivery has bounded exponential backoff');
 file_put_contents($output.'.mode','accept');$pdo->prepare('UPDATE familyhub_members SET active=0 WHERE scope_id=?')->execute([$scope]);$pdo->prepare('UPDATE familyhub_deliveries SET next_attempt=0 WHERE state=\'pending\' AND inbox_id IN (SELECT id FROM familyhub_inbox WHERE scope_id=?)')->execute([$scope]);$result=(new NativeDeliveryService($container))->run(1);check($result['cancelled']===1&&count(capture()['messages'])===1,'membership revoked before retry cancels delivery without SMTP leak');
 file_put_contents($output.'.mode','rejectEhlo');$transport=new \Kanboard\Plugin\FamilyHub\Model\NativeVerifiedSmtp('127.0.0.1',$port,'tls');$transport->setTimeout(2);try{$transport->start();$blocked=false;}catch(\Throwable$e){$blocked=true;}try{$transport->stop();}catch(\Throwable$e){}$verbs=capture()['verbs'];check($blocked&&!in_array('HELO',$verbs,true)&&!in_array('AUTH',$verbs,true),'requested STARTTLS cannot fall back to plaintext HELO/auth');
 file_put_contents($output.'.mode','accept');$transport=new \Kanboard\Plugin\FamilyHub\Model\NativeVerifiedSmtp('127.0.0.1',$port,'tls');$transport->setTimeout(2);try{$transport->start();$blocked=false;}catch(\Throwable$e){$blocked=true;}try{$transport->stop();}catch(\Throwable$e){}check($blocked&&in_array('STARTTLS',capture()['verbs'],true),'unavailable STARTTLS fails closed');
 $pdo->prepare('UPDATE familyhub_members SET active=1 WHERE scope_id=?')->execute([$scope]);
 $pdo->prepare('UPDATE familyhub_inbox_preferences SET settings=? WHERE scope_id=? AND account_id=? AND category=\'tasks\'')->execute([json_encode(['inApp'=>false,'sound'=>false,'push'=>false,'email'=>true]),$scope,$account]);
 $pdo->beginTransaction();$writer->insert($scope,$account,null,'task',$target,3,'task.updated','tasks','scope',hash('sha256',$prefix.':3'));$pdo->commit();$result=(new NativeDeliveryService($container))->run(1);check($result['accepted']===1 && count(capture()['messages'])===2,'email remains independent when in-app channel muted');
 $rows=(new \Kanboard\Plugin\FamilyHub\Model\NativeInboxService($container,'Bearer '.$token))->execute('inbox.sync',['cursor'=>0]);check(count(array_filter($rows['items'],fn($r)=>$r['targetRevision']===3))===0,'email-only immutable reference is excluded from in-app projection');
 $q=$pdo->prepare('SELECT id FROM familyhub_inbox WHERE scope_id=? AND target_revision=3');$q->execute([$scope]);$emailOnlyId=(int)$q->fetchColumn();$q->closeCursor();check((new \Kanboard\Plugin\FamilyHub\Model\NativeInboxService($container,'Bearer '.$token))->execute('inbox.open',['id'=>$emailOnlyId])['item']['id']===$emailOnlyId,'email-only open still revalidates current recipient ACL');
 $pdo->prepare('INSERT INTO familyhub_finance_policy(scope_id,enabled,revision,sequence) VALUES(?,1,1,0)')->execute([$scope]);$pdo->prepare('INSERT INTO familyhub_finance_grants VALUES(?,?,\'read\')')->execute([$scope,$account]);$pdo->prepare('INSERT INTO familyhub_inbox_preferences VALUES(?,?,\'finance\',?)')->execute([$scope,$account,json_encode(['inApp'=>true,'sound'=>false,'push'=>false,'email'=>true])]);
 $pdo->beginTransaction();$writer->insert($scope,$account,null,'financeEntry',uuid(),1,'financeEntry.created','finance','scope',hash('sha256',$prefix.':finance'));$pdo->commit();$pdo->prepare('UPDATE familyhub_finance_grants SET access_level=\'none\' WHERE scope_id=?')->execute([$scope]);$result=(new NativeDeliveryService($container))->run(1);check($result['cancelled']===1&&count(capture()['messages'])===2,'revoked finance grant cancels queued email before SMTP');
 echo 'SUCCESS '.$checks.' SMTP checks (local capture only)'.PHP_EOL;
}finally{proc_terminate($process);foreach($pipes as$p){if(is_resource($p)){fclose($p);}}proc_close($process);@unlink($output);@unlink($output.'.mode');}
