<?php
umask(0077);
define('FAMILYHUB_ACCOUNT_MAIL_KEY_BASE64',base64_encode(random_bytes(32)));
define('FAMILYHUB_SMTP_HOST','127.0.0.1');define('FAMILYHUB_SMTP_PORT',25252);define('FAMILYHUB_SMTP_ENCRYPTION','none');define('FAMILYHUB_SMTP_ALLOW_LOCAL_PLAINTEXT',true);define('FAMILYHUB_SMTP_FROM','sender@capture.invalid');define('FAMILYHUB_PUBLIC_URL','http://127.0.0.1:18380');
require '/var/www/app/app/common.php';if(session_status()===PHP_SESSION_ACTIVE){session_abort();}
if(!defined('FAMILYHUB_DEVELOPMENT_MODE')||FAMILYHUB_DEVELOPMENT_MODE!==true){throw new RuntimeException('Synthetic only');}
use Kanboard\Plugin\FamilyHub\Model\NativeService;
use Kanboard\Plugin\FamilyHub\Model\NativeError;
use Kanboard\Plugin\FamilyHub\Model\NativeAccountMailCrypto;
use Kanboard\Plugin\FamilyHub\Model\NativeInvitationMailQueue;
$pdo=$container['db']->getConnection();\Kanboard\Plugin\FamilyHub\Schema\SharingSchema::create($pdo,$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)!=='sqlite');\Kanboard\Plugin\FamilyHub\Schema\SharingSchema::create($pdo,$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)!=='sqlite');$service=new NativeService($container);$checks=0;$prefix='sharing_'.bin2hex(random_bytes(5));$ip='sharing-test-'.bin2hex(random_bytes(8));$password=bin2hex(random_bytes(16));$stamp='2026-10-10T10:00:00.000Z';
function check($v,$m){global$checks;if(!$v){throw new RuntimeException('FAIL: '.$m);}$checks++;echo 'PASS: '.$m.PHP_EOL;}
function q($s,$p=[]){global$pdo;$q=$pdo->prepare($s);$q->execute($p);$r=$q->fetchAll(PDO::FETCH_ASSOC);$q->closeCursor();return$r;}
function api($op,$p=[],$token=''){global$service,$ip;return$service->dispatch($op,$p,$token?'Bearer '.$token:'',$ip);}
function deny($op,$p,$token,$code){try{api($op,$p,$token);$ok=false;}catch(NativeError$e){$ok=$e->errorCode===$code;}check($ok,$op.' denies '.$code);}
function uuid(){ $h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20); }
function user($suffix){global$container,$prefix,$password;$email=$prefix.$suffix.'@capture.invalid';$container['userModel']->create(['username'=>$prefix.'_'.$suffix,'password'=>$password,'email'=>$email,'role'=>'app-user']);$session=api('auth.login',['username'=>$prefix.'_'.$suffix,'password'=>$password,'deviceName'=>'Sharing test']);q('INSERT INTO familyhub_email_identities(account_id,email,verified_at,revision) VALUES(?,?,?,1)',[$session['user']['accountId'],$email,time()]);$session['email']=$email;return$session;}
function invite($scope,$recipient,$owner,$role='member'){q('DELETE FROM familyhub_rate_limits WHERE id=?',[hash('sha256','invite-recipient:'.$recipient['email'])]);$r=api('invitations3.create',['scopeId'=>$scope['id'],'recipientEmail'=>$recipient['email'],'role'=>$role,'requestId'=>uuid(),'language'=>'sl','accessScope'=>$scope['kind']==='project'?'project':'space'],$owner['token']);api('invitations3.accept',['invitationId'=>$r['invitation']['id']],$recipient['token']);return$r;}
function operation($id,$type,$payload,$revision=0){return['opId'=>uuid(),'recordId'=>$id,'type'=>$type,'expectedRevision'=>$revision,'deleted'=>false,'payload'=>$payload];}
function push($scope,$id,$type,$p,$token,$revision=0){return api('sync3.push',['scopeId'=>$scope,'operation'=>operation($id,$type,$p,$revision),'operationContractVersion'=>3],$token);}
function project($title){global$stamp;return['title'=>$title,'description'=>'','area'=>'home','startAt'=>null,'endAt'=>null,'phases'=>[],'availabilityMinutes'=>null,'availabilityPeriod'=>null,'createdAt'=>$stamp,'updatedAt'=>$stamp];}
function task($pid,$assignees=[]){global$stamp;return['title'=>'Project task','notes'=>'','projectId'=>$pid,'dueAt'=>null,'isCompleted'=>false,'startAt'=>null,'endAt'=>null,'assigneeAccountIds'=>$assignees,'phaseId'=>null,'estimateMinutes'=>null,'availabilityMinutes'=>null,'availabilityPeriod'=>null,'timer'=>['elapsedSeconds'=>0,'runningSince'=>null,'runId'=>null],'assigneePersonId'=>null,'subjectPersonIds'=>[],'createdAt'=>$stamp,'updatedAt'=>$stamp];}
function account(){global$stamp;return['name'=>'Exclusive project ledger','currency'=>'EUR','openingBalanceMinor'=>0,'openingBalanceAt'=>null,'archived'=>false,'ownerAccountId'=>null,'createdAt'=>$stamp,'updatedAt'=>$stamp];}
function entry($aid,$tid){global$stamp;return['accountId'=>$aid,'kind'=>'expense','status'=>'planned','amountMinor'=>250,'currency'=>'EUR','title'=>'Project cost','notes'=>'','category'=>'','payerAccountId'=>null,'recipientAccountId'=>null,'occurredAt'=>$stamp,'plannedAt'=>null,'paidAt'=>null,'taskId'=>$tid,'ledgerAccountId'=>$aid,'payerPersonId'=>null,'recipientPersonId'=>null,'createdByPersonId'=>null,'recurrenceRuleId'=>null,'occurrenceKey'=>null,'createdAt'=>$stamp,'updatedAt'=>$stamp];}
function fpush($sid,$id,$type,$payload,$token){return api('finance2.push',['scopeId'=>$sid,'operation'=>operation($id,$type,$payload)],$token);}
$owner=user('owner');$full=user('full');$narrow=user('narrow');$viewer=user('viewer');$outsider=user('outsider');
$caps=api('capabilities');check($caps['spaceAccessPolicyVersions']===[3]&&$caps['features']['spaceProjectMembership'],'sharing3 capabilities advertised separately');
foreach(['organization','household'] as $kind){
 $root=api('scopes.create',['id'=>uuid(),'kind'=>$kind,'name'=>'Full '.$kind,'accessPolicyVersion'=>3,'requestId'=>uuid()],$owner['token'])['scope'];
 $child=api('scopes.create',['id'=>uuid(),'kind'=>'project','name'=>'Child '.$kind,'parentScopeId'=>$root['id'],'requestId'=>uuid()],$owner['token'])['scope'];
 check($child['parentScopeId']===$root['id']&&$child['parentScopeKind']===$kind&&$child['accessPolicyVersion']===3,'generic child parent wire '.$kind);
 $pending=api('invitations3.create',['scopeId'=>$root['id'],'recipientEmail'=>$full['email'],'role'=>'member','requestId'=>uuid(),'language'=>'sl','accessScope'=>'space'],$owner['token']);
 check($pending['invitation']['contractVersion']===3&&$pending['invitation']['accessScope']==='space'&&$pending['invitation']['sharedFinanceIncluded'],'explicit full space invitation '.$kind);
 $mail=q('SELECT * FROM familyhub_invitation_mail WHERE invitation_id=?',[$pending['invitation']['id']])[0];$secret=NativeAccountMailCrypto::decrypt($mail['token_cipher'],(new NativeInvitationMailQueue($container))->aad($mail['invitation_id']));check(str_starts_with($secret,'fhi3_'),'scoped email token version3');
 deny('sync3.pull',['scopeId'=>$child['id'],'cursor'=>0],$full['token'],'permission_revoked');
 api('invitations3.accept',['invitationId'=>$pending['invitation']['id']],$full['token']);invite($child,$narrow,$owner);invite($root,$viewer,$owner,'viewer');
 $listed=api('scopes.list',['includeOrganizations'=>true],$full['token'])['scopes'];$view=array_values(array_filter($listed,fn($s)=>$s['id']===$child['id']))[0];check($view['role']==='member'&&$view['accessSource']==='spaceMembership','full member inherits edit '.$kind);
 check(api('finance2.policy',['scopeId'=>$child['id']],$full['token'])['grant']==='write','full member finance write '.$kind);
 check(api('finance2.policy',['scopeId'=>$child['id']],$narrow['token'])['grant']==='write','project member finance write '.$kind);
 deny('sync3.pull',['scopeId'=>$root['id'],'cursor'=>0],$narrow['token'],'permission_revoked');deny('finance2.pull',['scopeId'=>$root['id'],'cursor'=>0],$narrow['token'],'permission_revoked');
 $future=api('scopes.create',['id'=>uuid(),'kind'=>'project','name'=>'Future child','parentScopeId'=>$root['id'],'requestId'=>uuid()],$owner['token'])['scope'];check(api('sync3.pull',['scopeId'=>$future['id'],'cursor'=>0],$full['token'])['records'][0]['id']===$future['id'],'member creates and inherits future children');deny('sync3.pull',['scopeId'=>$future['id'],'cursor'=>0],$narrow['token'],'permission_revoked');
 $tid=uuid();push($child['id'],$tid,'task',task($child['id'],[$full['user']['accountId']]),$owner['token']);check(count(api('inbox.sync',['cursor'=>0],$full['token'])['items'])>0,'inherited member receives assigned project notification');
 $aid=uuid();fpush($child['id'],$aid,'financeAccount',account(),$narrow['token']);check(api('finance2.pull',['scopeId'=>$child['id'],'cursor'=>0],$full['token'])['records'][0]['id']===$aid,'whole/project shared finance equality');
 deny('sync3.push',['scopeId'=>$child['id'],'operation'=>operation(uuid(),'task',task($child['id']))],$viewer['token'],'permission_revoked');deny('finance2.push',['scopeId'=>$child['id'],'operation'=>operation(uuid(),'financeAccount',account())],$viewer['token'],'finance_forbidden');
 check(count(api('scopes.members',['scopeId'=>$child['id']],$full['token'])['members'])===4,'member union includes inherited viewer');check(count(api('finance.grants',['scopeId'=>$child['id']],$narrow['token'])['grants'])===4,'finance grants effective member union');
 deny('invitations2.create',['scopeId'=>$root['id'],'recipientEmail'=>$outsider['email'],'role'=>'member','requestId'=>uuid(),'language'=>'sl'],$owner['token'],'client_upgrade_required');deny('invitations3.create',['scopeId'=>$child['id'],'recipientEmail'=>$outsider['email'],'role'=>'member','requestId'=>uuid(),'language'=>'sl','accessScope'=>'space'],$owner['token'],'validation_error');
 invite($child,$outsider,$narrow);check(api('sync3.pull',['scopeId'=>$child['id'],'cursor'=>0],$outsider['token'])['records'][0]['id']===$child['id'],'project member manages project invitation');deny('scopes.removeMember',['scopeId'=>$root['id'],'userId'=>$viewer['user']['id'],'requestId'=>uuid()],$narrow['token'],'permission_revoked');
 deny('scopes.removeMember',['scopeId'=>$root['id'],'userId'=>$owner['user']['id'],'requestId'=>uuid()],$full['token'],'cannot_remove_owner');
 $ownedByMember=api('scopes.create',['id'=>uuid(),'kind'=>'project','name'=>'Member-owned child','parentScopeId'=>$root['id'],'requestId'=>uuid()],$full['token'])['scope'];check($ownedByMember['role']==='owner','member creates independently owned child');
 invite($child,$full,$owner);api('scopes.removeMember',['scopeId'=>$root['id'],'userId'=>$full['user']['id'],'requestId'=>uuid()],$owner['token']);check(api('finance2.policy',['scopeId'=>$child['id']],$full['token'])['grant']==='write','independent project membership survives fullspace revoke');check(api('finance2.policy',['scopeId'=>$ownedByMember['id']],$full['token'])['grant']==='write','independent child ownership survives fullspace revoke');deny('sync3.pull',['scopeId'=>$future['id'],'cursor'=>0],$full['token'],'permission_revoked');
 api('scopes.removeMember',['scopeId'=>$child['id'],'userId'=>$full['user']['id'],'requestId'=>uuid()],$narrow['token']);deny('finance2.pull',['scopeId'=>$child['id'],'cursor'=>0],$full['token'],'permission_revoked');
 check(in_array($child['id'],api('scopes.list',['includeAccessChanges'=>true],$full['token'])['revokedScopeIds'],true),'positive revoke journal inherited and direct');
}
// Owner-reviewed migration, old invitations do not silently widen.
$legacy=api('scopes.create',['id'=>uuid(),'kind'=>'household','name'=>'Legacy','requestId'=>uuid()],$owner['token'])['scope'];$old=api('invitations.create',['scopeId'=>$legacy['id'],'recipientUsername'=>$outsider['user']['username'],'role'=>'member','requestId'=>uuid()],$owner['token']);$accepted=api('invitations.create',['scopeId'=>$legacy['id'],'recipientUsername'=>$full['user']['username'],'role'=>'member','requestId'=>uuid()],$owner['token']);api('invitations.accept',['token'=>$accepted['token']],$full['token']);
$preview=api('scopes.accessMigrationPreview',['scopeId'=>$legacy['id'],'targetVersion'=>3],$owner['token']);check(in_array($old['invitation']['id'],$preview['revokedInvitationIds'],true)&&count($preview['projects'][0]['additionalWriters'])>=1,'migration discloses new finance writers and revoked invitations');deny('scopes.accessMigrationApply',['scopeId'=>$legacy['id'],'targetVersion'=>3,'previewHash'=>$preview['previewHash'],'requestId'=>uuid()],$full['token'],'permission_revoked');$apply=['scopeId'=>$legacy['id'],'targetVersion'=>3,'previewHash'=>$preview['previewHash'],'requestId'=>uuid()];$migrated=api('scopes.accessMigrationApply',$apply,$owner['token']);check(api('scopes.accessMigrationApply',$apply,$owner['token'])===$migrated,'migration exact replay');deny('invitations.accept',['token'=>$old['token']],$outsider['token'],'invitation_invalid');check(api('finance2.policy',['scopeId'=>$legacy['id']],$full['token'])['grant']==='write','legacy member explicitly upgraded sharedfinance');
// Closed extraction preserves domains; old operations replay but fresh stale writes stop.
$pid=uuid();$tid=uuid();$eid=uuid();$aid=uuid();$fid=uuid();$person=uuid();push($legacy['id'],$person,'householdPerson',['name'=>'Project person','notes'=>'','archived'=>false,'createdAt'=>$stamp,'updatedAt'=>$stamp],$owner['token']);$projectOp=operation($pid,'project',project('Extracted'));$original=api('sync3.push',['scopeId'=>$legacy['id'],'operation'=>$projectOp],$owner['token']);$projectTask=task($pid);$projectTask['assigneePersonId']=$person;push($legacy['id'],$tid,'task',$projectTask,$owner['token']);$event=['title'=>'Meeting','notes'=>'','projectId'=>$pid,'startAt'=>$stamp,'endAt'=>null,'assigneeAccountIds'=>[],'createdAt'=>$stamp,'updatedAt'=>$stamp];push($legacy['id'],$eid,'event',$event,$owner['token']);$reminder=uuid();$reminderRequest=['id'=>$reminder,'scopeId'=>$legacy['id'],'targetType'=>'event','targetId'=>$eid,'remindAt'=>'2030-01-01T00:00:00.000Z','expectedRevision'=>0,'requestId'=>uuid()];$reminderReply=api('reminders.put',$reminderRequest,$full['token']);fpush($legacy['id'],$aid,'financeAccount',account(),$owner['token']);fpush($legacy['id'],$fid,'financeEntry',entry($aid,$tid),$owner['token']);$secondTask=uuid();$secondAccount=uuid();push($legacy['id'],$secondTask,'task',task($pid),$owner['token']);fpush($legacy['id'],$secondAccount,'financeAccount',account(),$owner['token']);fpush($legacy['id'],uuid(),'financeEntry',entry($secondAccount,$secondTask),$owner['token']);$transferPayload=['fromAccountId'=>$aid,'toAccountId'=>$secondAccount,'amountMinor'=>100,'currency'=>'EUR','status'=>'posted','title'=>'Project ledger transfer','notes'=>'','occurredAt'=>$stamp,'createdAt'=>$stamp,'updatedAt'=>$stamp];$closedTransfer=uuid();fpush($legacy['id'],$closedTransfer,'financeTransfer',$transferPayload,$owner['token']);$unrelatedAccount=uuid();fpush($legacy['id'],$unrelatedAccount,'financeAccount',account(),$owner['token']);fpush($legacy['id'],$tid,'financeEntry',entry($unrelatedAccount,null),$owner['token']);$unrelatedReminder=uuid();api('reminders.put',['id'=>$unrelatedReminder,'scopeId'=>$legacy['id'],'targetType'=>'financeEntry','targetId'=>$tid,'remindAt'=>'2030-01-01T00:00:00.000Z','expectedRevision'=>0,'requestId'=>uuid()],$full['token']);$other=uuid();push($legacy['id'],$other,'project',project('Remain household'),$owner['token']);
$preview=api('scopes.projectSharingPreview',['scopeId'=>$legacy['id'],'projectId'=>$pid],$full['token']);check($preview['canApply']&&count($preview['movedRecordIds'])===5 && $preview['movedReminderIds']===[$reminder]&&count($preview['movedFinanceRecordIds'])===5,'closed household project/finance graph preview');$apply=['scopeId'=>$legacy['id'],'projectId'=>$pid,'previewHash'=>$preview['previewHash'],'requestId'=>uuid()];$extracted=api('scopes.projectSharingApply',$apply,$full['token']);check($extracted['scope']['id']===$pid&&$extracted['scope']['parentScopeId']===$legacy['id'],'extraction stable project/root scope');check(api('scopes.projectSharingApply',$apply,$full['token'])===$extracted,'extraction uncertain response replay');invite($extracted['scope'],$narrow,$full);$records=api('sync3.pull',['scopeId'=>$pid,'cursor'=>0],$narrow['token'])['records'];check(count($records)===5&&!in_array($other,array_column($records,'id'),true),'narrow extracted project hides household remainder');check(count(api('reminders.list',['scopeId'=>$pid],$full['token'])['reminders'])===1,'extracted reminder follows project target');$eventInbox=array_values(array_filter(api('inbox.sync',['cursor'=>0],$full['token'])['items'],fn($i)=>$i['targetId']===$eid))[0];check($eventInbox['scopeId']===$pid&&api('inbox.open',['id'=>$eventInbox['id'],'recordContractVersion'=>3],$full['token'])['record']['id']===$eid,'stored inbox target follows extracted project');$updatedTask=$projectTask;$updatedTask['title']='After extraction';push($pid,$tid,'task',$updatedTask,$narrow['token'],1);check(true,'extracted person reference remains editable');check(count(api('finance2.pull',['scopeId'=>$pid,'cursor'=>0],$narrow['token'])['records'])===5,'narrow extracted finance closed ledger');deny('sync3.pull',['scopeId'=>$legacy['id'],'cursor'=>0],$narrow['token'],'permission_revoked');check(api('sync3.push',['scopeId'=>$legacy['id'],'operation'=>$projectOp],$owner['token'])['record']===$original['record'],'old accepted operation replay preserved after extraction');deny('sync3.push',['scopeId'=>$legacy['id'],'operation'=>operation($tid,'task',task($pid),1)],$owner['token'],'record_relocated');deny('finance2.push',['scopeId'=>$legacy['id'],'operation'=>operation($fid,'financeEntry',entry($aid,$tid),1)],$owner['token'],'record_relocated');
$unrelatedInbox=array_values(array_filter(api('inbox.sync',['cursor'=>0],$full['token'])['items'],fn($i)=>$i['targetId']===$tid && $i['targetType']==='financeEntry'))[0];check($unrelatedInbox['scopeId']===$legacy['id']&&q('SELECT scope_id FROM familyhub_reminders WHERE id=?',[$unrelatedReminder])[0]['scope_id']===$legacy['id'],'cross-table UUID collision never moves unrelated finance notification/reminder');
check(in_array($closedTransfer,$extracted['movedFinanceRecordIds'],true),'closed project account transfer migrates without duplicating cash');
// Shared account blocks extraction and keeps all rows intact.
$blocked=uuid();$bt=uuid();$ba=uuid();push($legacy['id'],$blocked,'project',project('Blocked project'),$owner['token']);push($legacy['id'],$bt,'task',task($blocked),$owner['token']);fpush($legacy['id'],$ba,'financeAccount',account(),$owner['token']);fpush($legacy['id'],uuid(),'financeEntry',entry($ba,$bt),$owner['token']);fpush($legacy['id'],uuid(),'financeEntry',entry($ba,null),$owner['token']);$p=api('scopes.projectSharingPreview',['scopeId'=>$legacy['id'],'projectId'=>$blocked],$owner['token']);check(!$p['canApply']&&in_array('project_finance_account_shared',array_column($p['blockers'],'code'),true),'shared financial account explicit blocker');deny('scopes.projectSharingApply',['scopeId'=>$legacy['id'],'projectId'=>$blocked,'previewHash'=>$p['previewHash'],'requestId'=>uuid()],$owner['token'],'project_sharing_blocked');check(!q('SELECT id FROM familyhub_scopes WHERE id=?',[$blocked]),'blocked extraction no partial child');
$solo=api('scopes.create',['id'=>uuid(),'kind'=>'project','name'=>'Standalone3','accessPolicyVersion'=>3,'requestId'=>uuid()],$owner['token']);check($solo['scope']['projectRootId']===$solo['scope']['id']&&isset($solo['projectRoot']),'standalone3 permanent root');invite($solo['scope'],$narrow,$owner);check(api('finance2.policy',['scopeId'=>$solo['scope']['id']],$narrow['token'])['grant']==='write','standalone project invite includes shared finances');
$externalLedger=uuid();fpush($legacy['id'],$externalLedger,'financeAccount',account(),$owner['token']);$crossTransfer=$transferPayload;$crossTransfer['fromAccountId']=$ba;$crossTransfer['toAccountId']=$externalLedger;fpush($legacy['id'],uuid(),'financeTransfer',$crossTransfer,$owner['token']);$crossPreview=api('scopes.projectSharingPreview',['scopeId'=>$legacy['id'],'projectId'=>$blocked],$owner['token']);check(in_array('project_transfer_cross_scope',array_column($crossPreview['blockers'],'code'),true),'transfer into household ledger stays explicit blocked dependency');
// Extraction preview is invalidated by a real concurrent edit, with no partial move.
$staleProject=uuid();push($legacy['id'],$staleProject,'project',project('Stale extraction'),$owner['token']);$stalePreview=api('scopes.projectSharingPreview',['scopeId'=>$legacy['id'],'projectId'=>$staleProject],$owner['token']);push($legacy['id'],$staleProject,'project',project('Changed after preview'),$full['token'],1);deny('scopes.projectSharingApply',['scopeId'=>$legacy['id'],'projectId'=>$staleProject,'previewHash'=>$stalePreview['previewHash'],'requestId'=>uuid()],$owner['token'],'project_sharing_preview_changed');check(!q('SELECT id FROM familyhub_scopes WHERE id=?',[$staleProject]),'stale preview creates no child');
// A parent viewer never erases stronger direct child membership from upgrade preview.
$legacyOrg=api('scopes.create',['id'=>uuid(),'kind'=>'organization','name'=>'Union migration','accessPolicyVersion'=>2,'requestId'=>uuid()],$owner['token'])['scope'];$legacyChild=api('scopes.create',['id'=>uuid(),'kind'=>'project','name'=>'Union child','organizationId'=>$legacyOrg['id'],'requestId'=>uuid()],$owner['token'])['scope'];foreach ([[$legacyOrg,'viewer'],[$legacyChild,'member']] as [$s,$role]) {$i=api('invitations.create',['scopeId'=>$s['id'],'recipientUsername'=>$viewer['user']['username'],'role'=>$role,'requestId'=>uuid()],$owner['token']);api('invitations.accept',['token'=>$i['token']],$viewer['token']);}
$unionPreview=api('scopes.accessMigrationPreview',['scopeId'=>$legacyOrg['id'],'targetVersion'=>3],$owner['token']);$childPreview=array_values(array_filter($unionPreview['projects'],fn($r)=>$r['scopeId']===$legacyChild['id']))[0];check(in_array($viewer['user']['accountId'],array_column($childPreview['additionalWriters'],'accountId'),true),'migration preview uses max direct and inherited role');api('scopes.accessMigrationApply',['scopeId'=>$legacyOrg['id'],'targetVersion'=>3,'previewHash'=>$unionPreview['previewHash'],'requestId'=>uuid()],$owner['token']);check(api('finance2.policy',['scopeId'=>$legacyChild['id']],$viewer['token'])['grant']==='write'&&api('finance2.policy',['scopeId'=>$legacyOrg['id']],$viewer['token'])['grant']==='read','explicit migration preserves child member and parent viewer boundaries');
// Viewer upgrades require a fresh explicit acceptance; viewer invitations never downgrade.
invite($solo['scope'],$viewer,$owner,'viewer');check(api('finance2.policy',['scopeId'=>$solo['scope']['id']],$viewer['token'])['grant']==='read','project viewer financial read');invite($solo['scope'],$viewer,$owner,'member');check(api('finance2.policy',['scopeId'=>$solo['scope']['id']],$viewer['token'])['grant']==='write','explicit accepted member invitation upgrades viewer');invite($solo['scope'],$viewer,$owner,'viewer');check(api('finance2.policy',['scopeId'=>$solo['scope']['id']],$viewer['token'])['grant']==='write','accepted viewer invitation cannot downgrade existing member');
$newEmail=$prefix.'new@capture.invalid';$newInvite=api('invitations3.create',['scopeId'=>$solo['scope']['id'],'recipientEmail'=>$newEmail,'role'=>'member','requestId'=>uuid(),'language'=>'sl','accessScope'=>'project'],$owner['token']);$job=q('SELECT * FROM familyhub_invitation_mail WHERE invitation_id=?',[$newInvite['invitation']['id']])[0];$token=NativeAccountMailCrypto::decrypt($job['token_cipher'],(new NativeInvitationMailQueue($container))->aad($job['invitation_id']));$reg=['token'=>$token,'username'=>$prefix.'_new','password'=>$password,'displayName'=>'New sharing recipient','deviceName'=>'Sharing3'];deny('auth.registerInvitation2',$reg,'','client_upgrade_required');$newSession=api('auth.registerInvitation3',$reg);check(api('scopes.list',[],$newSession['token'])['scopes']===[],'invitation3 registration never grants membership');deny('invitations2.accept',['token'=>$token],$newSession['token'],'client_upgrade_required');api('invitations3.accept',['token'=>$token],$newSession['token']);check(api('finance2.policy',['scopeId'=>$solo['scope']['id']],$newSession['token'])['grant']==='write','new registration requires explicit project acceptance');
deny('scopes.accessMigrationPreview',['scopeId'=>$root['id']],$owner['token'],'client_upgrade_required');deny('scopes.accessMigrationApply',['scopeId'=>$root['id'],'previewHash'=>'ignored','requestId'=>uuid()],$owner['token'],'client_upgrade_required');
check(api('reminders.put',$reminderRequest,$full['token'])===$reminderReply,'old accepted reminder operation replay preserved after extraction');
// Parent deletion detaches an independently owned child without downgrading policy3.
foreach (['organization','household'] as $kind) {
 $deleting=user('delete_'.$kind);$parent=api('scopes.create',['id'=>uuid(),'kind'=>$kind,'name'=>'Delete parent','accessPolicyVersion'=>3,'requestId'=>uuid()],$deleting['token'])['scope'];$ownedChild=api('scopes.create',['id'=>uuid(),'kind'=>'project','name'=>'Retained independent child','parentScopeId'=>$parent['id'],'requestId'=>uuid()],$deleting['token'])['scope'];invite($ownedChild,$full,$deleting);
 $plan=api('account.deletion.preview',['policyVersion'=>3],$deleting['token']);$parentPlan=array_values(array_filter($plan['ownedScopes'],fn($s)=>$s['id']===$parent['id']))[0];check($parentPlan['canDeleteScope'],'unshared parent can be deleted with detached independent child '.$kind);
 $resolutions=array_map(fn($r)=>['scopeId'=>$r['scopeId'],'recordId'=>$r['recordId'],'action'=>$r['action']],$plan['resolutions']);$result=api('account.deletion.confirm',['operationId'=>uuid(),'receiptToken'=>bin2hex(random_bytes(32)),'previewHash'=>$plan['previewHash'],'password'=>$password,'confirmation'=>'DELETE','policyVersion'=>3,'ownedScopeDeletions'=>[$parent['id']],'ownershipTransfers'=>[['scopeId'=>$ownedChild['id'],'successorAccountId'=>$full['user']['accountId']]],'resolutions'=>$resolutions],$deleting['token']);check($result['deleted'],'parent account deletion completes '.$kind);
 $remaining=q('SELECT * FROM familyhub_scopes WHERE id=?',[$ownedChild['id']])[0];check($remaining['parent_scope_id']===null&&(int)$remaining['access_policy_version']===3,'detached child preserves policy3 '.$kind);check(api('finance2.policy',['scopeId'=>$ownedChild['id']],$full['token'])['grant']==='write','independent child owner finance survives parent deletion '.$kind);
}
$private=api('personal.ensure',[],$owner['token'])['scope'];deny('finance2.pull',['scopeId'=>$private['id'],'cursor'=>0],$narrow['token'],'permission_revoked');
echo 'PASS: '.$checks.' scoped sharing checks ('.$pdo->getAttribute(PDO::ATTR_DRIVER_NAME).')'.PHP_EOL;
